# exp18

下記のNotebookの特徴量抽出を目的

https://www.kaggle.com/code/yoshiki001/amex-lightgbm-baseline-exp6/data?scriptVersionId=101497304

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display
import datetime
import warnings
import gc
import random
import time
import pickle
import os

from sklearn.metrics import plot_confusion_matrix
from sklearn.model_selection import StratifiedKFold
from sklearn.calibration import CalibrationDisplay
# import optuna.integration.lightgbm as lgb
import lightgbm as lgb
# from lightgbm import LGBMClassifier, log_evaluation
from tqdm.auto import tqdm

from tsfresh import extract_features
from tsfresh.feature_extraction import ComprehensiveFCParameters
from tsfresh import select_features
from tsfresh.utilities.dataframe_functions import impute

from sklearn.model_selection import train_test_split

In [2]:
# kaggle = True
IS_COLAB = False

In [3]:
class CFG:
    EXPERIMENT = 14 #実験管理No.
    NUM_NEIGHBOR = 20
    SEED = 42
    THRESHOLD = 0.5
    n_splits = 5
    target = "point_of_interest"
    
    del_col_list = ["B_29"] #,"target"]
    
    features_avg = ['B_1', 'B_2', 'B_3', 'B_4', 'B_5', 'B_6', 'B_8', 'B_9', 'B_10', 'B_11', 'B_12', 'B_13', 'B_14', 'B_15', 
                    'B_16', 'B_17', 'B_18', 'B_19', 'B_20', 'B_21', 'B_22', 'B_23', 'B_24', 'B_25', 'B_28', 'B_30', 
                    'B_32', 'B_33', 'B_37', 'B_38', 'B_39', 'B_40', 'B_41', 'B_42', 'D_39', 'D_41', 'D_42', 'D_43', 'D_44', 
                    'D_45', 'D_46', 'D_47', 'D_48', 'D_50', 'D_51', 'D_53', 'D_54', 'D_55', 'D_58', 'D_59', 'D_60', 'D_61', 
                    'D_62', 'D_65', 'D_66', 'D_69', 'D_70', 'D_71', 'D_72', 'D_73', 'D_74', 'D_75', 'D_76', 'D_77', 'D_78', 
                    'D_80', 'D_82', 'D_84', 'D_86', 'D_91', 'D_92', 'D_94', 'D_96', 'D_103', 'D_104', 'D_108', 'D_112', 
                    'D_113', 'D_114', 'D_115', 'D_117', 'D_118', 'D_119', 'D_120', 'D_121', 'D_122', 'D_123', 'D_124', 
                    'D_125', 'D_126', 'D_128', 'D_129', 'D_131', 'D_132', 'D_133', 'D_134', 'D_135', 'D_136', 'D_140', 
                    'D_141', 'D_142', 'D_144', 'D_145', 'P_2', 'P_3', 'P_4', 'R_1', 'R_2', 'R_3', 'R_7', 'R_8', 'R_9', 
                    'R_10', 'R_11', 'R_14', 'R_15', 'R_16', 'R_17', 'R_20', 'R_21', 'R_22', 'R_24', 'R_26', 'R_27', 'S_3', 
                    'S_5', 'S_6', 'S_7', 'S_9', 'S_11', 'S_12', 'S_13', 'S_15', 'S_16', 'S_18', 'S_22', 'S_23', 'S_25', 'S_26']
    features_std = ['B_1', 'B_2', 'B_3', 'B_4', 'B_5', 'B_6', 'B_8', 'B_9', 'B_10', 'B_11', 'B_12', 'B_13', 'B_14', 'B_15', 
                    'B_16', 'B_17', 'B_18', 'B_19', 'B_20', 'B_21', 'B_22', 'B_23', 'B_24', 'B_25', 'B_28', 'B_30', 
                    'B_32', 'B_33', 'B_37', 'B_38', 'B_39', 'B_40', 'B_41', 'B_42', 'D_39', 'D_41', 'D_42', 'D_43', 'D_44', 
                    'D_45', 'D_46', 'D_47', 'D_48', 'D_50', 'D_51', 'D_53', 'D_54', 'D_55', 'D_58', 'D_59', 'D_60', 'D_61', 
                    'D_62', 'D_65', 'D_66', 'D_69', 'D_70', 'D_71', 'D_72', 'D_73', 'D_74', 'D_75', 'D_76', 'D_77', 'D_78', 
                    'D_80', 'D_82', 'D_84', 'D_86', 'D_91', 'D_92', 'D_94', 'D_96', 'D_103', 'D_104', 'D_108', 'D_112', 
                    'D_113', 'D_114', 'D_115', 'D_117', 'D_118', 'D_119', 'D_120', 'D_121', 'D_122', 'D_123', 'D_124', 
                    'D_125', 'D_126', 'D_128', 'D_129', 'D_131', 'D_132', 'D_133', 'D_134', 'D_135', 'D_136', 'D_140', 
                    'D_141', 'D_142', 'D_144', 'D_145', 'P_2', 'P_3', 'P_4', 'R_1', 'R_2', 'R_3', 'R_7', 'R_8', 'R_9', 
                    'R_10', 'R_11', 'R_14', 'R_15', 'R_16', 'R_17', 'R_20', 'R_21', 'R_22', 'R_24', 'R_26', 'R_27', 'S_3', 
                    'S_5', 'S_6', 'S_7', 'S_9', 'S_11', 'S_12', 'S_13', 'S_15', 'S_16', 'S_18', 'S_22', 'S_23', 'S_25', 'S_26']
    features_min = ['B_2', 'B_4', 'B_5', 'B_9', 'B_13', 'B_14', 'B_15', 'B_16', 'B_17', 'B_19', 'B_20', 'B_28', 'B_33', 
                    'B_36', 'B_42', 'D_39', 'D_41', 'D_42', 'D_45', 'D_46', 'D_48', 'D_50', 'D_51', 'D_53', 'D_55', 'D_56', 'D_58', 
                    'D_59', 'D_60', 'D_62', 'D_70', 'D_71', 'D_74', 'D_75', 'D_78', 'D_83', 'D_102', 'D_112', 'D_113', 'D_115', 
                    'D_118', 'D_119', 'D_121', 'D_122', 'D_128', 'D_132', 'D_140', 'D_141', 'D_144', 'D_145', 'P_2', 'P_3', 'R_1', 
                    'R_27', 'S_3', 'S_5', 'S_7', 'S_9', 'S_11', 'S_12', 'S_23', 'S_25']
    features_max = ['B_1', 'B_2', 'B_3', 'B_4', 'B_5', 'B_6', 'B_7', 'B_8', 'B_9', 'B_10', 'B_12', 'B_13', 'B_14', 'B_15', 'B_16', 
                    'B_17', 'B_18', 'B_19', 'B_21', 'B_23', 'B_24', 'B_25', 'B_30', 'B_33', 'B_37', 'B_38', 'B_39', 'B_40', 
                    'B_42', 'D_39', 'D_41', 'D_42', 'D_43', 'D_44', 'D_45', 'D_46', 'D_47', 'D_48', 'D_49', 'D_50', 'D_52', 'D_55', 
                    'D_56', 'D_58', 'D_59', 'D_60', 'D_61', 'D_63', 'D_64', 'D_65', 'D_70', 'D_71', 'D_72', 'D_73', 'D_74', 'D_76', 
                    'D_77', 'D_78', 'D_80', 'D_82', 'D_84', 'D_91', 'D_102', 'D_105', 'D_107', 'D_110', 'D_111', 'D_112', 'D_115', 
                    'D_116', 'D_117', 'D_118', 'D_119', 'D_121', 'D_122', 'D_123', 'D_124', 'D_125', 'D_126', 'D_128', 'D_131', 
                    'D_132', 'D_133', 'D_134', 'D_135', 'D_136', 'D_138', 'D_140', 'D_141', 'D_142', 'D_144', 'D_145', 'P_2', 'P_3', 
                    'P_4', 'R_1', 'R_3', 'R_5', 'R_6', 'R_7', 'R_8', 'R_10', 'R_11', 'R_14', 'R_17', 'R_20', 'R_26', 'R_27', 'S_3', 
                    'S_5', 'S_7', 'S_8', 'S_11', 'S_12', 'S_13', 'S_15', 'S_16', 'S_22', 'S_23', 'S_24', 'S_25', 'S_26', 'S_27']
    features_last = ['B_1', 'B_2', 'B_3', 'B_4', 'B_5', 'B_6', 'B_7', 'B_8', 'B_9', 'B_10', 'B_11', 'B_12', 'B_13', 'B_14', 'B_15', 
                     'B_16', 'B_17', 'B_18', 'B_19', 'B_20', 'B_21', 'B_22', 'B_23', 'B_24', 'B_25', 'B_26', 'B_28', 'B_30', 
                     'B_32', 'B_33', 'B_36', 'B_37', 'B_38', 'B_39', 'B_40', 'B_41', 'B_42', 'D_39', 'D_41', 'D_42', 'D_43', 'D_44', 
                     'D_45', 'D_46', 'D_47', 'D_48', 'D_49', 'D_50', 'D_51', 'D_52', 'D_53', 'D_54', 'D_55', 'D_56', 'D_58', 'D_59', 
                     'D_60', 'D_61', 'D_62', 'D_63', 'D_64', 'D_65', 'D_69', 'D_70', 'D_71', 'D_72', 'D_73', 'D_75', 'D_76', 'D_77', 
                     'D_78', 'D_79', 'D_80', 'D_81', 'D_82', 'D_83', 'D_86', 'D_91', 'D_96', 'D_105', 'D_106', 'D_112', 'D_114', 'D_119', 
                     'D_120', 'D_121', 'D_122', 'D_124', 'D_125', 'D_126', 'D_127', 'D_130', 'D_131', 'D_132', 'D_133', 'D_134', 'D_138', 
                     'D_140', 'D_141', 'D_142', 'D_145', 'P_2', 'P_3', 'P_4', 'R_1', 'R_2', 'R_3', 'R_4', 'R_5', 'R_6', 'R_7', 'R_8', 'R_9', 
                     'R_10', 'R_11', 'R_12', 'R_13', 'R_14', 'R_15', 'R_19', 'R_20', 'R_26', 'R_27', 'S_3', 'S_5', 'S_6', 'S_7', 'S_8', 'S_9', 
                     'S_11', 'S_12', 'S_13', 'S_16', 'S_19', 'S_20', 'S_22', 'S_23', 'S_24', 'S_25', 'S_26', 'S_27']
    


# Path setting

if IS_COLAB:
    data_dir = '../input/amex-default-prediction'
    save_dir = f'/content/drive/MyDrive/Kaggle/Amex-DefaultPrediction/exp/exp-{EXPERIMENT}'
    !mkdir -p {save_dir}
else:
    data_dir = '../input/amex-default-prediction'
    save_dir = './'

print(f"data_dir : {data_dir}")
print(f"save_dir : {save_dir}")
    
def seed_everything(seed):
    random.seed(seed)
    np.random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    
seed_everything(CFG.SEED)

data_dir : ../input/amex-default-prediction
save_dir : ./

In [4]:
def amex_metric(y_true: np.array, y_pred: np.array) -> float:

    # count of positives and negatives
    n_pos = y_true.sum()
    n_neg = y_true.shape[0] - n_pos

    # sorting by descring prediction values
    indices = np.argsort(y_pred)[::-1]
    preds, target = y_pred[indices], y_true[indices]

    # filter the top 4% by cumulative row weights
    weight = 20.0 - target * 19.0
    cum_norm_weight = (weight / weight.sum()).cumsum()
    four_pct_filter = cum_norm_weight <= 0.04

    # default rate captured at 4%
    d = target[four_pct_filter].sum() / n_pos

    # weighted gini coefficient
    lorentz = (target / n_pos).cumsum()
    gini = ((lorentz - cum_norm_weight) * weight).sum()

    # max weighted gini coefficient
    gini_max = 10 * n_neg * (1 - 19 / (n_pos + 20 * n_neg))

    # normalized weighted gini coefficient
    g = gini / gini_max

    return 0.5 * (g + d)

def lgb_amex_metric(y_true, y_pred):
    """The competition metric with lightgbm's calling convention"""
    return ('amex',
            amex_metric(y_true, y_pred),
            True)

In [5]:
def statistics(df,
               features_avg = CFG.features_avg,
               features_std = CFG.features_std,
               features_min = CFG.features_min,
               features_max = CFG.features_max,
               features_last = CFG.features_last):
    
    cid = pd.Categorical(df.pop('customer_ID'), ordered=True)
    last = (cid != np.roll(cid, -1)) # mask for last statement of every customer
    
    df_avg = (df
              .groupby(cid)
              .mean()[features_avg]
              .rename(columns={f: f"{f}_avg" for f in features_avg})
             )
    gc.collect()
    print('Computed avg')
    
    df_std = (df
              .groupby(cid)
              .mean()[features_std]
              .rename(columns={f: f"{f}_std" for f in features_std})
             )
    gc.collect()
    print('Computed std')
    
    df_min = (df
              .groupby(cid)
              .min()[features_min]
              .rename(columns={f: f"{f}_min" for f in features_min})
             )
    gc.collect()
    print('Computed min')
    
    df_max = (df
              .groupby(cid)
              .max()[features_max]
              .rename(columns={f: f"{f}_max" for f in features_max})
             )
    gc.collect()
    print('Computed max')
    
    df_last = (df.loc[last, features_last]
          .rename(columns={f: f"{f}_last" for f in features_last})
          .set_index(np.asarray(cid[last]))
         )
    gc.collect()
    print('Computed last')
    
    df = pd.concat([df_last, df_min, df_max, df_avg, df_std], axis=1)
    del df_last, df_avg, df_std, df_min, df_max, cid, last
    gc.collect
              
    return df

# data load

In [6]:
# start_time  = time.time()
df_train = pd.read_parquet(f'../input/AMEXdata-integerdtypes-parquetformat/train.parquet')
df_label = pd.read_csv(f'../input/amex-default-prediction/train_labels.csv')
# end_time  = time.time()
# print(f"read time：{int(end_time - start_time)}s")
print(df_train.shape)

(5531451, 190)

In [7]:
# df_train.loc[2700014:, :]

In [8]:

# データを絞る
df_train2 = df_train.loc[2700015:, :]
df_train = df_train.loc[0:2700014, :]
# df_train2 = df_train.loc[319997:, :]

df_train.drop(columns = CFG.del_col_list,inplace = True)
df_train2.drop(columns = CFG.del_col_list,inplace = True)

print(f"df_train : {df_train.shape}")
display(df_train)
print(f"df_train2 : {df_train2.shape}")
display(df_train2)
print(f"df_label : {df_label.shape}")
display(df_label.head())

df_train : (2700015, 189)

,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
0,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-03-09,0.938469,0,0.008724,1.006838,0.009228,0.124035,0.0,0.004709,...,-1,-1,-1,0,0,0.0,NaN,0,0.000610,0
1,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-04-07,0.936665,0,0.004923,1.000653,0.006151,0.126750,0.0,0.002714,...,-1,-1,-1,0,0,0.0,NaN,0,0.005492,0
2,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-05-28,0.954180,3,0.021655,1.009672,0.006815,0.123977,0.0,0.009423,...,-1,-1,-1,0,0,0.0,NaN,0,0.006986,0
3,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-06-13,0.960384,0,0.013683,1.002700,0.001373,0.117169,0.0,0.005531,...,-1,-1,-1,0,0,0.0,NaN,0,0.006527,0
4,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-07-16,0.947248,0,0.015193,1.000727,0.007605,0.117325,0.0,0.009312,...,-1,-1,-1,0,0,0.0,NaN,0,0.008126,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2700010,7ca1addc5e1caa8dfe98e3f88a606734aed393728cc9c7...,2017-11-16,0.712959,0,0.004683,0.814162,0.004070,NaN,0.0,0.000792,...,-1,-1,-1,0,0,0.0,NaN,0,0.006212,0
2700011,7ca1addc5e1caa8dfe98e3f88a606734aed393728cc9c7...,2017-12-16,0.717567,0,0.002866,0.817167,0.004758,NaN,0.0,0.003424,...,-1,-1,-1,0,0,0.0,NaN,0,0.005307,0
2700012,7ca1addc5e1caa8dfe98e3f88a606734aed393728cc9c7...,2018-01-17,0.721974,0,0.001875,0.819956,0.008918,NaN,0.0,0.004029,...,-1,-1,-1,0,0,0.0,NaN,0,0.008508,0
2700013,7ca1addc5e1caa8dfe98e3f88a606734aed393728cc9c7...,2018-02-14,0.709065,0,0.009156,0.813486,0.003509,NaN,0.0,0.000635,...,-1,-1,-1,0,0,0.0,NaN,0,0.000701,0
2700014,7ca1addc5e1caa8dfe98e3f88a606734aed393728cc9c7...,2018-03-17,0.713721,0,0.007944,0.817886,0.009880,NaN,0.0,0.009914,...,-1,-1,-1,0,0,0.0,NaN,0,0.000488,0

df_train2 : (2831436, 189)

,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
2700015,7ca1ccd1234a5f18f5c9bdf843348e1b559261c5a7bdad...,2017-03-11,0.850266,0,0.000575,0.812974,0.005458,NaN,0.0,0.004501,...,-1,-1,-1,0,0,0.0,NaN,0,0.004787,0
2700016,7ca1ccd1234a5f18f5c9bdf843348e1b559261c5a7bdad...,2017-04-09,0.802441,0,0.005421,0.817911,0.509102,NaN,0.0,0.007012,...,-1,-1,-1,0,0,0.0,NaN,0,0.001837,0
2700017,7ca1ccd1234a5f18f5c9bdf843348e1b559261c5a7bdad...,2017-06-16,0.808068,0,0.004112,0.811541,0.004994,NaN,0.0,0.002847,...,-1,-1,-1,0,0,0.0,NaN,0,0.003195,0
2700018,7ca1ccd1234a5f18f5c9bdf843348e1b559261c5a7bdad...,2017-07-17,0.899655,0,0.009328,0.818695,0.001953,NaN,0.0,0.002305,...,-1,-1,-1,0,0,0.0,NaN,0,0.000980,0
2700019,7ca1ccd1234a5f18f5c9bdf843348e1b559261c5a7bdad...,2017-08-11,0.920872,0,0.044814,0.810695,0.008201,0.181002,0.0,0.007473,...,-1,-1,-1,0,0,0.0,NaN,0,0.009529,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5531446,fffff1d38b785cef84adeace64f8f83db3a0c31e8d92ea...,2017-11-05,0.979333,14,0.020818,0.828199,0.003487,0.090743,0.0,0.025139,...,-1,-1,-1,0,0,0.0,NaN,0,0.001498,0
5531447,fffff1d38b785cef84adeace64f8f83db3a0c31e8d92ea...,2017-12-23,0.984907,10,0.007209,0.812610,0.005904,0.079886,0.0,0.023691,...,-1,-1,-1,0,0,0.0,NaN,0,0.008225,0
5531448,fffff1d38b785cef84adeace64f8f83db3a0c31e8d92ea...,2018-01-06,0.983019,15,0.013151,0.815422,0.003457,0.100503,0.0,0.012343,...,-1,-1,-1,0,0,0.0,NaN,0,0.006773,0
5531449,fffff1d38b785cef84adeace64f8f83db3a0c31e8d92ea...,2018-02-06,0.969861,15,0.009855,1.003541,0.005117,0.101802,0.0,0.008578,...,-1,-1,-1,0,0,0.0,NaN,0,0.001168,0
5531450,fffff1d38b785cef84adeace64f8f83db3a0c31e8d92ea...,2018-03-14,0.982175,0,0.000077,0.992880,0.000809,0.119165,0.0,0.014092,...,-1,-1,-1,0,0,0.0,NaN,0,0.003184,0

df_label : (458913, 2)

                                         customer_ID  target
0  0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...       0
1  00000fd6641609c6ece5454664794f0340ad84dddce9a2...       0
2  00001b22f846c82c51f6e3958ccd81970162bae8b007e8...       0
3  000041bdba6ecadd89a52d11886e8eaaec9325906c9723...       0
4  00007889e4fcd2614b6cbe7f8f3d2e5c728eca32d9eb8a...       0

# tsfresh で特徴量作成

In [9]:
#時系列特徴量を作成
fc_parameters = {
    'c3' : [{'lag': 1},{'lag': 3}]
#     'partial_autocorrelation': [{'lag': 1},{'lag': 3}, {'lag': 5}, {'lag': 7}, {'lag': 9}],
    #"autocorrelation": [{'lag': 1}, {'lag': 3}, {'lag': 5}, {'lag': 7}, {'lag': 12}],
}

df_ts = df_train.copy()
df_ts = df_ts.fillna(0)
df_ts = extract_features(df_ts, column_id="customer_ID", column_sort="S_2", default_fc_parameters=fc_parameters)

#列名変更
col_list = list(df_ts)
print(len(col_list))
for idx in tqdm(range(len(col_list))):
    col_tmp = col_list[idx].replace('"','')
    df_ts = df_ts.rename(columns={col_list[idx]:col_tmp})
    

df_ts.reset_index(inplace = True)
df_ts = df_ts.rename(columns = {"index":"customer_ID"})
print(df_ts.shape)
df_ts.head()

Feature Extraction: 100%|██████████| 40/40 [41:12<00:00, 61.81s/it]

374

  0%|          | 0/374 [00:00<?, ?it/s]

(223920, 375)

,customer_ID,P_2__c3__lag_1,P_2__c3__lag_3,D_39__c3__lag_1,D_39__c3__lag_3,B_1__c3__lag_1,B_1__c3__lag_3,B_2__c3__lag_1,B_2__c3__lag_3,R_1__c3__lag_1,...,D_141__c3__lag_1,D_141__c3__lag_3,D_142__c3__lag_1,D_142__c3__lag_3,D_143__c3__lag_1,D_143__c3__lag_3,D_144__c3__lag_1,D_144__c3__lag_3,D_145__c3__lag_1,D_145__c3__lag_3
0,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,0.813242,0.813953,0.000000,0.0,1.696306e-06,1.469749e-06,1.014646,1.014703,7.065906e-08,...,0.0,0.0,0.0,0.0,0.0,0.0,1.632297e-07,1.670906e-07,0.0,0.0
1,00000fd6641609c6ece5454664794f0340ad84dddce9a2...,0.727988,0.727797,323.272727,11.0,1.683358e-05,5.839084e-06,0.965557,0.962951,2.492636e-07,...,0.0,0.0,0.0,0.0,0.0,0.0,7.725995e-08,9.789814e-08,0.0,0.0
2,00001b22f846c82c51f6e3958ccd81970162bae8b007e8...,0.677608,0.677666,0.000000,0.0,9.719315e-08,6.050499e-08,0.543240,0.542959,3.006458e-07,...,0.0,0.0,0.0,0.0,0.0,0.0,8.013915e-08,1.048687e-07,0.0,0.0
3,000041bdba6ecadd89a52d11886e8eaaec9325906c9723...,0.216082,0.215422,0.000000,0.0,7.253920e-04,3.850624e-05,0.893162,0.892970,1.978877e-07,...,0.0,0.0,0.0,0.0,0.0,0.0,1.086618e-07,1.073078e-07,0.0,0.0
4,00007889e4fcd2614b6cbe7f8f3d2e5c728eca32d9eb8a...,0.704600,0.694645,0.000000,0.0,2.278486e-07,1.735253e-07,0.540028,0.540371,5.286286e-08,...,0.0,0.0,0.0,0.0,0.0,0.0,5.300711e-08,5.776780e-08,0.0,0.0

In [10]:
df_ts.to_pickle("../output/exp18_tsfresh/train_c3_1.pkl")

In [11]:
del df_ts
gc.collect

In [12]:
#時系列特徴量を作成
fc_parameters = {
    'c3' : [{'lag': 1},{'lag': 3}]
#     'partial_autocorrelation': [{'lag': 1},{'lag': 3}, {'lag': 5}, {'lag': 7}, {'lag': 9}],
    #"autocorrelation": [{'lag': 1}, {'lag': 3}, {'lag': 5}, {'lag': 7}, {'lag': 12}],
}

df_ts2 = df_train2.copy()
df_ts2 = df_ts2.fillna(0)
df_ts2 = extract_features(df_ts2, column_id="customer_ID", column_sort="S_2", default_fc_parameters=fc_parameters)

#列名変更
col_list = list(df_ts2)
print(len(col_list))
for idx in tqdm(range(len(col_list))):
    col_tmp = col_list[idx].replace('"','')
    df_ts2 = df_ts2.rename(columns={col_list[idx]:col_tmp})
    

df_ts2.reset_index(inplace = True)
df_ts2 = df_ts2.rename(columns = {"index":"customer_ID"})
print(df_ts2.shape)
df_ts2.head()

Feature Extraction: 100%|██████████| 40/40 [43:51<00:00, 65.78s/it]

374

  0%|          | 0/374 [00:00<?, ?it/s]

(234993, 375)

,customer_ID,P_2__c3__lag_1,P_2__c3__lag_3,D_39__c3__lag_1,D_39__c3__lag_3,B_1__c3__lag_1,B_1__c3__lag_3,B_2__c3__lag_1,B_2__c3__lag_3,R_1__c3__lag_1,...,D_141__c3__lag_1,D_141__c3__lag_3,D_142__c3__lag_1,D_142__c3__lag_3,D_143__c3__lag_1,D_143__c3__lag_3,D_144__c3__lag_1,D_144__c3__lag_3,D_145__c3__lag_1,D_145__c3__lag_3
0,7ca1ccd1234a5f18f5c9bdf843348e1b559261c5a7bdad...,0.663823,0.669153,0.0,0.0,1.980600e-05,2.059303e-06,0.420284,0.559605,1.930500e-06,...,0.0,0.0,0.0,0.0,0.0,0.0,3.947919e-08,2.575890e-08,0.0,0.0
1,7ca1f9f7732cf988864ba28fae198f46680e30eda87681...,0.574345,0.615439,0.0,0.0,3.592168e-06,1.430797e-05,0.928286,0.824644,6.455901e-08,...,0.0,0.0,0.0,0.0,0.0,0.0,1.267946e-07,2.184954e-07,0.0,0.0
2,7ca1fdc286b54e698886f473e1d020674c94c16f68ac88...,0.739911,0.734816,0.0,0.0,1.968103e-07,2.428556e-07,0.539039,0.539094,5.780547e-08,...,0.0,0.0,0.0,0.0,0.0,0.0,3.268264e-08,5.525725e-08,0.0,0.0
3,7ca2713ea23116fc72afde132b868c678c79ff152310a9...,0.560985,0.565235,0.0,0.0,5.500759e-08,1.234569e-07,0.542630,0.543521,4.605608e-08,...,0.0,0.0,0.0,0.0,0.0,0.0,1.403612e-07,2.044952e-07,0.0,0.0
4,7ca27fba28a327aad042af4879fc1d9e62c0e4ca087905...,0.000000,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0

In [13]:
df_ts2.to_pickle("../output/exp18_tsfresh/train_c3_2.pkl")

del df_ts2
gc.collect

In [ ]:
# train_ts = pd.concat([df_ts,df_ts2],axis =0)
pd.concat([df_ts,df_ts2],axis =0)["customer_ID"].value_counts()

In [ ]:
df_ts = pd.merge(df_ts,df_label,how = "left",on = "customer_ID")
df_ts = df_ts.fillna(0)
df_ts.head()

features_ts = df_ts.columns.values.tolist()
del features_ts[0]
del features_ts[-1]

In [ ]:
impute(df_ts[features_ts])
features_filtered = select_features(df_ts[features_ts], df_ts["target"])


df_ts = pd.concat([df_ts["customer_ID"],features_filtered], axis=1) 
df_ts.head()

In [ ]:
df_ts.to_pickle("../output/exp18_tsfresh/train_partial_autocorrelation.pkl")

# test data

In [14]:
# start_time  = time.time()
df_test = pd.read_parquet(f'../input/AMEXdata-integerdtypes-parquetformat/test.parquet')
# df_label = pd.read_csv(f'../input/amex-default-prediction/train_labels.csv')
# end_time  = time.time()
# print(f"read time：{int(end_time - start_time)}s")
print(df_test.shape)

(11363762, 190)

In [15]:

# データを絞る
df_test4 = df_test.loc[9000004:, :]
df_test3 = df_test.loc[6000008 : 9000003, :]
df_test2 = df_test.loc[3000003 : 6000007, :]
df_test = df_test.loc[:3000002, :]
# df_train2 = df_train.loc[319997:, :]

df_test4.drop(columns = CFG.del_col_list,inplace = True)
df_test3.drop(columns = CFG.del_col_list,inplace = True)
df_test2.drop(columns = CFG.del_col_list,inplace = True)
df_test.drop(columns = CFG.del_col_list,inplace = True)

print(f"df_train4 : {df_test4.shape}")
display(df_test4)
print(f"df_train3 : {df_test3.shape}")
display(df_test3)
print(f"df_train2 : {df_test2.shape}")
display(df_test2)
print(f"df_train : {df_test.shape}")
display(df_test)
# print(f"df_label : {df_label.shape}")
# display(df_label.head())

df_train4 : (2363758, 189)

,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
9000004,cabf72f4586c858d1d608b67ae65ef54ffb58e8a6eb756...,2018-04-06,0.510918,0,0.376521,0.058089,0.0,0.023386,0.000000,0.317657,...,-1,-1,-1,1,0,0.975251,1.026669,1,0.008092,7
9000005,cabf72f4586c858d1d608b67ae65ef54ffb58e8a6eb756...,2018-05-12,0.541776,0,0.424949,0.138636,0.0,0.011334,0.000000,0.240197,...,-1,-1,-1,1,0,0.979036,1.038021,1,0.000747,7
9000006,cabf72f4586c858d1d608b67ae65ef54ffb58e8a6eb756...,2018-06-20,0.541180,24,0.408738,0.183899,0.0,0.062212,0.000000,0.213130,...,-1,-1,-1,1,0,0.973832,1.035362,1,0.004034,7
9000007,cabf72f4586c858d1d608b67ae65ef54ffb58e8a6eb756...,2018-07-03,0.544475,0,0.453791,0.002540,0.0,0.100396,0.448303,0.139571,...,-1,-1,-1,1,1,0.980534,1.041126,1,0.002800,7
9000008,cabf72f4586c858d1d608b67ae65ef54ffb58e8a6eb756...,2018-08-02,0.538129,6,0.384210,0.245083,0.0,0.049164,0.317656,0.129984,...,-1,-1,-1,1,0,0.976562,1.044057,1,0.000648,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11363757,fffffa7cf7e453e1acc6a1426475d5cb9400859f82ff61...,2018-12-19,0.440834,0,0.008638,0.818277,0.0,NaN,0.000000,0.002710,...,-1,-1,-1,0,0,0.000000,NaN,0,0.005519,0
11363758,fffffa7cf7e453e1acc6a1426475d5cb9400859f82ff61...,2019-01-19,0.445590,0,0.009636,0.815558,0.0,NaN,0.000000,0.006921,...,-1,-1,-1,0,0,0.000000,NaN,0,0.000256,0
11363759,fffffa7cf7e453e1acc6a1426475d5cb9400859f82ff61...,2019-02-17,0.460082,0,0.004420,0.818864,0.0,NaN,0.000000,0.007058,...,-1,-1,-1,0,0,0.000000,NaN,0,0.003594,0
11363760,fffffa7cf7e453e1acc6a1426475d5cb9400859f82ff61...,2019-03-19,0.460331,0,0.009529,0.816313,0.0,NaN,0.000000,0.006851,...,-1,-1,-1,0,0,0.000000,NaN,0,0.005605,0
11363761,fffffa7cf7e453e1acc6a1426475d5cb9400859f82ff61...,2019-04-18,0.454546,0,0.000346,0.810128,0.0,NaN,0.000000,0.003494,...,-1,-1,-1,0,0,0.000000,NaN,0,0.006442,0

df_train3 : (2999996, 189)

,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
6000008,876213b012edd993afb3ca4581a439e7a49e9357174265...,2018-04-24,0.461459,1,0.200967,0.105575,0.000000,NaN,0.0,0.344969,...,-1,-1,-1,0,0,0.000000,NaN,0,0.000821,0
6000009,876213b012edd993afb3ca4581a439e7a49e9357174265...,2018-05-25,0.458031,1,0.194242,0.056117,0.000000,NaN,0.0,0.295153,...,-1,-1,-1,0,0,0.000000,NaN,0,0.005216,0
6000010,876213b012edd993afb3ca4581a439e7a49e9357174265...,2018-06-23,0.451473,1,0.185936,0.048469,0.000000,NaN,0.0,0.335627,...,-1,-1,-1,0,0,0.000000,NaN,0,0.006534,0
6000011,876213b012edd993afb3ca4581a439e7a49e9357174265...,2018-07-25,0.462734,1,0.185629,0.021260,0.000000,NaN,0.0,0.414759,...,-1,-1,-1,0,0,0.000000,NaN,0,0.006088,0
6000012,876213b012edd993afb3ca4581a439e7a49e9357174265...,2018-08-25,0.470269,1,0.183483,0.028222,0.000000,NaN,0.0,0.540095,...,-1,-1,-1,0,0,0.000000,NaN,0,0.009769,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8999999,cabf66520093fdb315416b42483d0bbb2e0c2304021628...,2018-12-08,0.293175,0,0.025930,1.007366,0.000000,0.728491,0.0,0.004385,...,-1,-1,-1,1,0,0.936329,0.371820,1,0.110658,1
9000000,cabf66520093fdb315416b42483d0bbb2e0c2304021628...,2019-01-07,0.261275,20,0.022896,1.009787,0.503804,0.687139,0.0,0.005323,...,-1,-1,-1,1,0,0.943055,0.382743,1,0.111948,1
9000001,cabf66520093fdb315416b42483d0bbb2e0c2304021628...,2019-02-12,0.216539,0,0.032676,1.006361,0.000000,0.746671,0.0,0.002182,...,-1,-1,-1,1,0,0.944817,0.389999,1,0.113005,1
9000002,cabf66520093fdb315416b42483d0bbb2e0c2304021628...,2019-03-09,0.224774,0,0.016797,1.003733,0.000000,0.695025,0.0,0.008588,...,-1,-1,-1,1,0,0.940652,0.387478,1,0.107700,1
9000003,cabf66520093fdb315416b42483d0bbb2e0c2304021628...,2019-04-25,0.367357,8,0.030567,1.004689,0.500092,0.665004,0.0,0.005664,...,-1,-1,-1,1,0,0.947842,0.399951,1,0.095418,1

df_train2 : (3000005, 189)

,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
3000003,438facfe1c0e2ed1ea4a21fb42bdbdd69c76bb1beb3124...,2018-04-16,0.760268,24,0.058704,1.000076,0.0,0.146872,0.0,0.012108,...,-1,-1,-1,0,0,0.0,NaN,0,0.000917,0
3000004,438facfe1c0e2ed1ea4a21fb42bdbdd69c76bb1beb3124...,2018-05-02,0.706184,10,0.033020,1.004698,0.0,0.137581,0.0,0.004694,...,-1,-1,-1,0,0,0.0,NaN,0,0.003071,0
3000005,438facfe1c0e2ed1ea4a21fb42bdbdd69c76bb1beb3124...,2018-06-08,0.708075,16,0.037176,1.006077,0.0,0.141268,0.0,0.010306,...,-1,-1,-1,0,0,0.0,NaN,0,0.004894,0
3000006,438facfe1c0e2ed1ea4a21fb42bdbdd69c76bb1beb3124...,2018-07-17,0.784049,0,0.014914,1.003832,0.0,0.148238,0.0,0.005454,...,-1,-1,-1,0,0,0.0,NaN,0,0.008214,0
3000007,438facfe1c0e2ed1ea4a21fb42bdbdd69c76bb1beb3124...,2018-08-08,0.782525,16,0.018579,1.007697,0.0,0.139968,0.0,0.007551,...,-1,-1,-1,0,0,0.0,NaN,0,0.003520,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6000003,8761f423a2400c05958312aa959e326e21a4b7bd4b6d6f...,2018-12-01,-0.044987,3,0.238707,0.021902,0.0,0.431843,0.0,0.559855,...,-1,-1,-1,0,0,0.0,NaN,0,0.007928,0
6000004,8761f423a2400c05958312aa959e326e21a4b7bd4b6d6f...,2019-01-08,0.001318,11,0.286718,0.021085,0.0,0.414760,0.0,0.572315,...,-1,-1,-1,0,0,0.0,NaN,0,0.008311,0
6000005,8761f423a2400c05958312aa959e326e21a4b7bd4b6d6f...,2019-02-23,0.002829,0,0.437064,0.025714,0.0,0.568931,0.0,0.643761,...,-1,-1,-1,0,0,0.0,NaN,0,0.009217,0
6000006,8761f423a2400c05958312aa959e326e21a4b7bd4b6d6f...,2019-03-03,0.003127,5,0.447009,0.033330,0.0,0.576812,0.0,0.545944,...,-1,-1,-1,0,0,0.0,NaN,0,0.001836,0
6000007,8761f423a2400c05958312aa959e326e21a4b7bd4b6d6f...,2019-04-23,-0.007836,0,0.435405,0.025535,0.0,0.601276,0.0,0.669332,...,-1,-1,-1,0,0,0.0,NaN,0,0.007206,0

df_train : (3000003, 189)

,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
0,00000469ba478561f23a92a868bd366de6f6527a684c9a...,2019-02-19,0.631315,0,0.010728,0.814497,0.000000,0.168651,0.000000,0.002347,...,-1,-1,-1,-1,0,NaN,NaN,-1,0.008281,-1
1,00000469ba478561f23a92a868bd366de6f6527a684c9a...,2019-03-25,0.587042,0,0.011026,0.810848,0.000000,0.241389,0.000000,0.009132,...,-1,-1,-1,0,0,0.0,NaN,0,0.003753,0
2,00000469ba478561f23a92a868bd366de6f6527a684c9a...,2019-04-25,0.609056,0,0.016390,1.004620,0.000000,0.266976,0.000000,0.004192,...,-1,-1,-1,0,0,0.0,NaN,0,0.002156,0
3,00000469ba478561f23a92a868bd366de6f6527a684c9a...,2019-05-20,0.614911,0,0.021672,0.816549,0.000000,0.188947,0.000000,0.015325,...,-1,-1,-1,0,0,0.0,NaN,0,0.005206,0
4,00000469ba478561f23a92a868bd366de6f6527a684c9a...,2019-06-15,0.591673,8,0.015923,0.810456,0.000000,0.180035,0.000000,0.011281,...,-1,-1,-1,0,0,0.0,NaN,0,0.007421,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999998,438fa8d88caf5b3bd3eeb66051a287424d1be254eec18e...,2019-06-11,-0.039915,0,0.112348,0.063397,1.507205,0.117318,0.812247,0.490812,...,-1,-1,-1,0,0,0.0,NaN,0,0.000251,0
2999999,438fa8d88caf5b3bd3eeb66051a287424d1be254eec18e...,2019-07-14,-0.044687,0,0.125577,1.007518,0.000000,0.136764,0.636750,0.288608,...,-1,-1,-1,0,0,0.0,NaN,0,0.005466,0
3000000,438fa8d88caf5b3bd3eeb66051a287424d1be254eec18e...,2019-08-11,0.009289,28,0.164369,0.033993,0.256839,0.220910,0.658336,0.464125,...,-1,-1,-1,0,0,0.0,NaN,0,0.003927,0
3000001,438fa8d88caf5b3bd3eeb66051a287424d1be254eec18e...,2019-09-14,-0.077925,61,0.183628,1.008675,1.254776,0.211177,1.357713,0.142302,...,-1,-1,-1,0,0,0.0,NaN,0,0.009140,0
3000002,438fa8d88caf5b3bd3eeb66051a287424d1be254eec18e...,2019-10-16,-0.138612,62,0.176163,0.044528,0.000000,0.208091,1.680080,0.379287,...,-1,-1,-1,0,0,0.0,NaN,0,0.009343,0

# tsfresh で特徴量作成

In [16]:
#時系列特徴量を作成
fc_parameters = {
    'c3' : [{'lag': 1},{'lag': 3}]
#     'partial_autocorrelation': [{'lag': 1},{'lag': 3}, {'lag': 5}, {'lag': 7}, {'lag': 9}],
    #"autocorrelation": [{'lag': 1}, {'lag': 3}, {'lag': 5}, {'lag': 7}, {'lag': 12}],
}

df_ts = df_test.copy()
df_ts = df_ts.fillna(0)
df_ts = extract_features(df_ts, column_id="customer_ID", column_sort="S_2", default_fc_parameters=fc_parameters)

#列名変更
col_list = list(df_ts)
print(len(col_list))
for idx in tqdm(range(len(col_list))):
    col_tmp = col_list[idx].replace('"','')
    df_ts = df_ts.rename(columns={col_list[idx]:col_tmp})
    

df_ts.reset_index(inplace = True)
df_ts = df_ts.rename(columns = {"index":"customer_ID"})
print(df_ts.shape)
df_ts.head()

Feature Extraction: 100%|██████████| 40/40 [45:51<00:00, 68.79s/it]

374

  0%|          | 0/374 [00:00<?, ?it/s]

(244057, 375)

,customer_ID,P_2__c3__lag_1,P_2__c3__lag_3,D_39__c3__lag_1,D_39__c3__lag_3,B_1__c3__lag_1,B_1__c3__lag_3,B_2__c3__lag_1,B_2__c3__lag_3,R_1__c3__lag_1,...,D_141__c3__lag_1,D_141__c3__lag_3,D_142__c3__lag_1,D_142__c3__lag_3,D_143__c3__lag_1,D_143__c3__lag_3,D_144__c3__lag_1,D_144__c3__lag_3,D_145__c3__lag_1,D_145__c3__lag_3
0,00000469ba478561f23a92a868bd366de6f6527a684c9a...,0.218528,0.217860,0.000000,0.000000,0.000003,0.000003,0.708740,0.738579,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,2.008549e-07,1.602559e-07,0.0,0.0
1,00001bf2e77ff879fab36aa4fac689b9ba411dae63ae39...,0.635630,0.630904,0.000000,0.000000,0.000100,0.000103,1.010603,1.010534,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,1.316376e-07,1.932984e-07,0.0,0.0
2,0000210045da4f81e5f122c6bde5c2a617d03eef67f82c...,0.431496,0.441915,104.181818,0.000000,0.000002,0.000001,0.729017,0.734542,0.0,...,0.698808,0.697953,0.002162,0.002130,1.0,1.0,5.945314e-02,5.825249e-02,1.0,1.0
3,00003b41e58ede33b8daf61ab56d9952f17c9ad1c3976c...,0.104611,0.103935,4092.000000,4635.142857,0.025427,0.024675,0.000782,0.000812,0.0,...,0.753232,0.752337,0.012960,0.012808,1.0,1.0,9.344688e-02,8.953851e-02,8.0,8.0
4,00004b22eaeeeb0ec976890c1d9bfc14fd9427e98c4ee9...,0.037275,0.034788,1240.818182,1404.285714,0.099365,0.095571,0.000084,0.000057,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,1.112858e-07,6.629426e-08,0.0,0.0

In [17]:
# df_ts.to_pickle("../output/exp18_tsfresh/train_partial_autocorrelation.pkl")
df_ts.to_pickle("../output/exp18_tsfresh/test_c3_1.pkl")

del df_ts
gc.collect

In [18]:
#時系列特徴量を作成
fc_parameters = {
    'c3' : [{'lag': 1},{'lag': 3}]
#     'partial_autocorrelation': [{'lag': 1},{'lag': 3}, {'lag': 5}, {'lag': 7}, {'lag': 9}],
    #"autocorrelation": [{'lag': 1}, {'lag': 3}, {'lag': 5}, {'lag': 7}, {'lag': 12}],
}

df_ts = df_test2.copy()
df_ts = df_ts.fillna(0)
df_ts = extract_features(df_ts, column_id="customer_ID", column_sort="S_2", default_fc_parameters=fc_parameters)

#列名変更
col_list = list(df_ts)
print(len(col_list))
for idx in tqdm(range(len(col_list))):
    col_tmp = col_list[idx].replace('"','')
    df_ts = df_ts.rename(columns={col_list[idx]:col_tmp})
    

df_ts.reset_index(inplace = True)
df_ts = df_ts.rename(columns = {"index":"customer_ID"})
print(df_ts.shape)
df_ts.head()

Feature Extraction: 100%|██████████| 40/40 [45:55<00:00, 68.88s/it]

374

  0%|          | 0/374 [00:00<?, ?it/s]

(244199, 375)

,customer_ID,P_2__c3__lag_1,P_2__c3__lag_3,D_39__c3__lag_1,D_39__c3__lag_3,B_1__c3__lag_1,B_1__c3__lag_3,B_2__c3__lag_1,B_2__c3__lag_3,R_1__c3__lag_1,...,D_141__c3__lag_1,D_141__c3__lag_3,D_142__c3__lag_1,D_142__c3__lag_3,D_143__c3__lag_1,D_143__c3__lag_3,D_144__c3__lag_1,D_144__c3__lag_3,D_145__c3__lag_1,D_145__c3__lag_3
0,438facfe1c0e2ed1ea4a21fb42bdbdd69c76bb1beb3124...,0.465026,0.470329,538.181818,1080.142857,0.000070,0.000044,0.838723,0.832406,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1.108408e-07,1.316262e-07,0.000000,0.000000
1,438fc929cfbdeb8406668e5f93b0a1d8701b495b7a3c97...,0.535987,0.535634,1.444444,1.200000,0.480162,0.479519,0.000017,0.000052,0.000000,...,0.916939,0.825736,0.301826,0.270851,0.777778,0.6,3.426099e-01,3.079563e-01,0.777778,0.600000
2,438fcb5097aeef654d867bc01825300f67ecd10d38a8ae...,0.033551,0.020158,6736.545455,4532.857143,0.010915,0.007178,0.005687,0.000290,0.023155,...,0.645776,0.646082,0.000800,0.000752,1.000000,1.0,1.252777e-07,1.352671e-07,22.181818,17.428571
3,438fe33bb7aedd27201159f30d291ec870d0e17b8fde19...,0.239940,0.218222,119.000000,123.400000,0.018827,0.014923,0.000038,0.000053,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1.422098e-07,8.939760e-08,0.000000,0.000000
4,438fe45931f2a777c27eda4d566f6cd497217ad29f5250...,0.256518,0.233931,1198.666667,-8693.200000,0.000813,0.000570,0.006387,0.009709,0.139067,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1.551751e-07,2.540895e-07,0.000000,0.000000

In [19]:
df_ts.to_pickle("../output/exp18_tsfresh/test_c3_2.pkl")

del df_ts
gc.collect

In [20]:
#時系列特徴量を作成
fc_parameters = {
    'c3' : [{'lag': 1},{'lag': 3}]
#     'partial_autocorrelation': [{'lag': 1},{'lag': 3}, {'lag': 5}, {'lag': 7}, {'lag': 9}],
    #"autocorrelation": [{'lag': 1}, {'lag': 3}, {'lag': 5}, {'lag': 7}, {'lag': 12}],
}

df_ts = df_test3.copy()
df_ts = df_ts.fillna(0)
df_ts = extract_features(df_ts, column_id="customer_ID", column_sort="S_2", default_fc_parameters=fc_parameters)

#列名変更
col_list = list(df_ts)
print(len(col_list))
for idx in tqdm(range(len(col_list))):
    col_tmp = col_list[idx].replace('"','')
    df_ts = df_ts.rename(columns={col_list[idx]:col_tmp})
    

df_ts.reset_index(inplace = True)
df_ts = df_ts.rename(columns = {"index":"customer_ID"})
print(df_ts.shape)
df_ts.head()

Feature Extraction: 100%|██████████| 40/40 [45:48<00:00, 68.71s/it]

374

  0%|          | 0/374 [00:00<?, ?it/s]

(243954, 375)

,customer_ID,P_2__c3__lag_1,P_2__c3__lag_3,D_39__c3__lag_1,D_39__c3__lag_3,B_1__c3__lag_1,B_1__c3__lag_3,B_2__c3__lag_1,B_2__c3__lag_3,R_1__c3__lag_1,...,D_141__c3__lag_1,D_141__c3__lag_3,D_142__c3__lag_1,D_142__c3__lag_3,D_143__c3__lag_1,D_143__c3__lag_3,D_144__c3__lag_1,D_144__c3__lag_3,D_145__c3__lag_1,D_145__c3__lag_3
0,876213b012edd993afb3ca4581a439e7a49e9357174265...,0.125162,0.126553,1.000000,1.142857,9.594488e-03,8.365331e-03,0.000062,0.000048,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,8.388998e-08,7.340667e-08,0.0,0.0
1,87624bf386274fa01a5c24d175ad7667de3b33906449a1...,0.041454,0.038073,299.727273,11.714286,5.239229e-01,5.171610e-01,0.000024,0.000037,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.135170e-08,2.491023e-08,0.0,0.0
2,8762606278a9aa2a8e466d21844e98787f637d61dffebe...,0.788254,0.783688,0.000000,0.000000,3.347826e-06,8.867474e-07,0.697071,0.667752,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.546767e-07,1.333259e-07,0.0,0.0
3,876266a9bd9be32e9ef0936e35f53de1ffdbe13955ff41...,0.417635,0.405012,0.363636,0.000000,8.576166e-07,4.368938e-07,0.395322,0.312153,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,9.853319e-08,8.102543e-08,0.0,0.0
4,87626a443f3a235a6fe9c3d92fe54744042681d0b5ed4a...,0.584998,0.589966,662.181818,464.571429,3.848047e-05,3.052806e-05,1.013960,1.014291,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,5.068073e-08,4.949302e-08,0.0,0.0

In [21]:
df_ts.to_pickle("../output/exp18_tsfresh/test_c3_3.pkl")

del df_ts
gc.collect

In [ ]:
#時系列特徴量を作成
fc_parameters = {
    'c3' : [{'lag': 1},{'lag': 3}]
#     'partial_autocorrelation': [{'lag': 1},{'lag': 3}, {'lag': 5}, {'lag': 7}, {'lag': 9}],
    #"autocorrelation": [{'lag': 1}, {'lag': 3}, {'lag': 5}, {'lag': 7}, {'lag': 12}],
}

df_ts = df_test4.copy()
df_ts = df_ts.fillna(0)
df_ts = extract_features(df_ts, column_id="customer_ID", column_sort="S_2", default_fc_parameters=fc_parameters)

#列名変更
col_list = list(df_ts)
print(len(col_list))
for idx in tqdm(range(len(col_list))):
    col_tmp = col_list[idx].replace('"','')
    df_ts = df_ts.rename(columns={col_list[idx]:col_tmp})
    

df_ts.reset_index(inplace = True)
df_ts = df_ts.rename(columns = {"index":"customer_ID"})
print(df_ts.shape)
df_ts.head()

Feature Extraction:  75%|███████▌  | 30/40 [27:07<08:55, 53.60s/it]

In [ ]:
df_ts.to_pickle("../output/exp18_tsfresh/test_c3_4.pkl")

del df_ts
gc.collect

# データのconcat

In [32]:
train1 = pd.read_pickle("../output/exp18_tsfresh/train_ts_1.pkl")
train2 = pd.read_pickle("../output/exp18_tsfresh/train_ts_2.pkl")

test1 = pd.read_pickle("../output/exp18_tsfresh/test_ts_1.pkl")
test2 = pd.read_pickle("../output/exp18_tsfresh/test_ts_2.pkl")
test3 = pd.read_pickle("../output/exp18_tsfresh/test_ts_3.pkl")
test4 = pd.read_pickle("../output/exp18_tsfresh/test_ts_4.pkl")

In [46]:
train = pd.concat([train1,train2],axis = 0).reset_index(drop = True)
test = pd.concat([test1,test2,test3,test4],axis = 0).reset_index(drop = True)

In [45]:
pd.concat([train1,train2],axis = 0).reset_index(drop = True)

,customer_ID,P_2__partial_autocorrelation__lag_1,P_2__partial_autocorrelation__lag_3,P_2__partial_autocorrelation__lag_5,P_2__partial_autocorrelation__lag_7,P_2__partial_autocorrelation__lag_9,D_39__partial_autocorrelation__lag_1,D_39__partial_autocorrelation__lag_3,D_39__partial_autocorrelation__lag_5,D_39__partial_autocorrelation__lag_7,...,D_144__partial_autocorrelation__lag_1,D_144__partial_autocorrelation__lag_3,D_144__partial_autocorrelation__lag_5,D_144__partial_autocorrelation__lag_7,D_144__partial_autocorrelation__lag_9,D_145__partial_autocorrelation__lag_1,D_145__partial_autocorrelation__lag_3,D_145__partial_autocorrelation__lag_5,D_145__partial_autocorrelation__lag_7,D_145__partial_autocorrelation__lag_9
0,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,0.174903,0.038565,-0.231226,NaN,NaN,-0.097222,-0.050758,-0.074767,NaN,...,-0.104158,-0.092795,0.351244,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,00000fd6641609c6ece5454664794f0340ad84dddce9a2...,0.687463,-0.001181,-0.136232,NaN,NaN,-0.110304,-0.434409,-0.168746,NaN,...,-0.232295,0.205815,-0.279658,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00001b22f846c82c51f6e3958ccd81970162bae8b007e8...,-0.088271,-0.220730,0.157298,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.171315,-0.585431,-0.213653,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,000041bdba6ecadd89a52d11886e8eaaec9325906c9723...,0.790905,0.261312,-0.042040,NaN,NaN,0.016960,0.189809,-0.397537,NaN,...,-0.079493,-0.346509,0.473548,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00007889e4fcd2614b6cbe7f8f3d2e5c728eca32d9eb8a...,0.469236,-0.078519,-0.436281,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.134475,-0.041639,0.374328,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
458908,ffff41c8a52833b56430603969b9ca48d208e7c192c6a4...,0.307777,0.181309,-0.120889,NaN,NaN,-0.225899,-0.487596,-0.239992,NaN,...,-0.027197,0.449531,0.981200,NaN,NaN,NaN,NaN,NaN,NaN,NaN
458909,ffff518bb2075e4816ee3fe9f3b152c57fc0e6f01bf7fd...,0.474588,-0.209672,0.030027,NaN,NaN,-0.165968,-0.031532,-0.060834,NaN,...,0.212008,0.191458,0.711614,NaN,NaN,NaN,NaN,NaN,NaN,NaN
458910,ffff9984b999fccb2b6127635ed0736dda94e544e67e02...,0.355944,-0.243459,-0.304177,NaN,NaN,-0.089064,0.574528,-0.048612,NaN,...,-0.085655,-0.110862,0.086914,NaN,NaN,-0.097222,-0.050758,-0.074767,NaN,NaN
458911,ffffa5c46bc8de74f5a4554e74e239c8dee6b9baf38814...,0.580295,-0.076159,0.198638,NaN,NaN,-0.022984,-0.195551,-0.340931,NaN,...,-0.114447,-0.370415,-0.387256,NaN,NaN,NaN,NaN,NaN,NaN,NaN
458912,fffff1d38b785cef84adeace64f8f83db3a0c31e8d92ea...,0.426032,-0.194253,0.008390,NaN,NaN,-0.271258,-0.057308,-1.824506,NaN,...,0.104276,-0.295171,0.869217,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
test['customer_ID'].unique

<bound method Series.unique of 0         00000469ba478561f23a92a868bd366de6f6527a684c9a...
1         00001bf2e77ff879fab36aa4fac689b9ba411dae63ae39...
2         0000210045da4f81e5f122c6bde5c2a617d03eef67f82c...
3         00003b41e58ede33b8daf61ab56d9952f17c9ad1c3976c...
4         00004b22eaeeeb0ec976890c1d9bfc14fd9427e98c4ee9...
                                ...
924616    ffff952c631f2c911b8a2a8ca56ea6e656309a83d2f64c...
924617    ffffcf5df59e5e0bba2a5ac4578a34e2b5aa64a1546cd3...
924618    ffffd61f098cc056dbd7d2a21380c4804bbfe60856f475...
924619    ffffddef1fc3643ea179c93245b68dca0f36941cd83977...
924620    fffffa7cf7e453e1acc6a1426475d5cb9400859f82ff61...
Name: customer_ID, Length: 924621, dtype: object>

In [55]:
test['customer_ID'].tail()

924616    ffff952c631f2c911b8a2a8ca56ea6e656309a83d2f64c...
924617    ffffcf5df59e5e0bba2a5ac4578a34e2b5aa64a1546cd3...
924618    ffffd61f098cc056dbd7d2a21380c4804bbfe60856f475...
924619    ffffddef1fc3643ea179c93245b68dca0f36941cd83977...
924620    fffffa7cf7e453e1acc6a1426475d5cb9400859f82ff61...
Name: customer_ID, dtype: object

###  たぶんOK

In [56]:
train.to_pickle("../output/exp18_tsfresh/train_partial_autocorrelation.pkl")

In [57]:
test.to_pickle("../output/exp18_tsfresh/test_partial_autocorrelation.pkl")

# 欠損値確認

In [61]:
train["P_2__partial_autocorrelation__lag_7"].isnull().sum()

458913

In [86]:
##　8割以上欠損値の列をDrop

drop_list = []

for col in list(train.columns):
    if train[col].isnull().sum() > (len(train) * 0.8):
        drop_list.append(col)
        
display(len(drop_list))

599

In [89]:
train = train.drop(columns = drop_list,axis = 1)
test = test.drop(columns = drop_list,axis = 1)

In [91]:
train.to_pickle("../output/exp18_tsfresh/train_partial_autocorrelation.pkl")
test.to_pickle("../output/exp18_tsfresh/test_partial_autocorrelation.pkl")