# Expressions of Gluttony

下記のNotebookだが、中身見たらただの闇のアンサンブルだったため無視。
https://www.kaggle.com/code/jazivxt/expressions-of-gluttony

In [1]:
from catboost import CatBoostClassifier
import gc; gc.enable()
from sklearn import *
import pandas as pd
import numpy as np
import numba, os

In [4]:

sub1 = pd.read_csv('../input/ensemble-weighted-average/submission.csv')
traini = pd.read_csv('../input/amex-default-prediction/train_data.csv', parse_dates=['S_2'], chunksize=400_000, iterator=True)
testi = pd.read_csv('../input/amex-default-prediction/test_data.csv', parse_dates=['S_2'], chunksize=400_000, iterator=True) 
labels = pd.read_csv('../input/amex-default-prediction/train_labels.csv')

In [7]:
# ? pd.read_csv

In [5]:
traini

In [8]:
%%time
train = []
for df in traini:
    print("chunk df size",df.shape)
    if len(train)>0: train = pd.concat([train, df])
    else: train = df[:]
    train.sort_values(by=['S_2'], inplace=True)
    train.reset_index(drop=True, inplace=True)
    train.drop_duplicates(subset=['customer_ID'], keep='last', inplace=True)
    del df; gc.collect()
train = pd.merge(train, labels, how='inner', on=['customer_ID'])
del labels; gc.collect()
col = [c for c in train if c not in ['customer_ID', 'target','S_2']]
train.fillna(0).to_csv('train.csv', index=False)

display(train.head(10))

del train; del traini; gc.collect()

test = []
for df in testi:
    print("chunk df size",df.shape)
    if len(test)>0: test = pd.concat([test, df])
    else: test = df[:]
    test.sort_values(by=['S_2'], inplace=True)
    test.reset_index(drop=True, inplace=True)
    test.drop_duplicates(subset=['customer_ID'], keep='last', inplace=True)
    del df; gc.collect()
test.fillna(0).to_csv('test.csv', index=False)
display(test.head(10))
del test; del testi; gc.collect()

chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (331451, 190)

,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,...,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145,target
0,9953a565dbe5c969b877e8e0998a564242904ca9ba33d8...,2018-03-01,0.483128,0.590818,0.039548,1.007066,0.008181,0.060718,0.009631,0.004932,...,NaN,NaN,0.000107,0.007353,0.008219,NaN,0.009328,0.009437,0.002835,1
1,f732d6fa2e1e6499b26524aacb5c0f3ec5b34923aa31ac...,2018-03-01,0.966223,0.008740,0.015001,1.005475,0.000270,0.094729,0.003222,0.007811,...,NaN,NaN,0.006807,0.002271,0.000613,NaN,0.009303,0.006770,0.007839,0
2,8c355c0455dedcb8f4f099c024c38b49e053045af7adde...,2018-03-01,0.933835,0.595937,0.024031,1.001446,0.009673,0.124648,0.000600,0.009576,...,NaN,NaN,0.001764,0.000134,0.003616,NaN,0.000337,0.006450,0.002954,0
3,1ad1a4b524a1be1d0b195a76bf3e2aedd722815dca2783...,2018-03-01,0.968357,0.001551,0.012611,1.006676,0.003375,0.084371,0.007597,0.003809,...,NaN,NaN,0.001110,0.006795,0.004939,NaN,0.006574,0.000900,0.001232,0
4,3faa8637e4b7447e14e6a9b6f74b858db19074b27b471f...,2018-03-01,0.684776,0.009670,0.040139,0.819089,0.008056,0.151762,0.006550,0.003981,...,NaN,NaN,0.009034,0.009141,0.006965,NaN,0.007663,0.007472,0.002779,0
5,205a8e4d474d4d94cdb313b6d56740196222a1e5d06f3b...,2018-03-01,0.905160,0.006385,0.009407,1.000161,0.007421,0.106522,0.001224,0.010183,...,NaN,NaN,0.006550,0.006891,0.009556,NaN,0.003725,0.006838,0.008829,0
6,ba13052830d2164f40133efb1331d6806493abb9205c08...,2018-03-01,0.327650,0.296355,0.663662,0.026866,0.006308,0.839686,0.005759,0.680529,...,NaN,NaN,0.007518,0.008346,0.009591,NaN,0.008786,0.009273,0.005012,1
7,6f0013b1244e47446b955410babde28d6b475a16282c13...,2018-03-01,-0.058050,0.002495,0.483644,0.021503,1.009134,0.645047,1.025524,0.867613,...,NaN,NaN,0.008906,0.000007,0.005338,NaN,0.003372,0.006684,0.009068,1
8,1b0763be9ba6460480fcbe1106651832ae72e585dcbd0c...,2018-03-01,0.531856,0.589495,0.296786,0.054451,0.001441,0.172772,0.297200,0.620404,...,NaN,NaN,0.004286,0.009506,0.007337,NaN,0.009536,0.000188,0.009862,0
9,d174d2438ddbf06d10f31389d25be0ea81caf40ae8ae31...,2018-03-01,0.449045,0.710619,0.637013,0.043832,1.006491,0.529772,0.239392,0.368570,...,NaN,NaN,0.005201,0.005358,0.002733,NaN,0.009892,0.002874,0.001517,0

chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (400000, 190)
chunk df size (163762, 190)

,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
111818,fcfbfcd2b4272c58e8deb490229fd4c5cc52ee60f86ad8...,2019-04-01,0.045833,0.176903,0.217835,0.042806,1.007260,0.150600,0.196969,0.627736,...,NaN,NaN,NaN,0.003634,0.006348,0.006796,NaN,0.001377,0.004456,0.007931
111819,fdd222f0a1a7f5627832d2ad76f6173be051640d16e560...,2019-04-01,0.864736,0.007885,0.025065,1.006404,0.002986,0.118205,0.003036,0.007826,...,NaN,NaN,NaN,0.007570,0.006029,0.003809,NaN,0.006030,0.002311,0.002854
111820,fdb7e8c2901d786fe27b0600dfec1a5ff5528c7d0fd165...,2019-04-01,0.641887,0.000572,0.338517,0.064841,0.003296,0.308590,0.000084,0.281035,...,NaN,NaN,NaN,0.005402,0.005729,0.003977,NaN,0.003859,0.005934,0.000661
111821,ff3047110541794d216370c5abd154d82a5b67048742cc...,2019-04-01,0.999726,0.000712,0.029428,1.000179,0.000045,0.085342,0.003971,0.008599,...,NaN,NaN,NaN,0.005877,0.005309,0.006816,NaN,0.003756,0.002241,0.009942
111823,fcaee6f58f4de77007a3f555890512b3aef68819d79dd2...,2019-04-01,0.845940,0.001031,0.005087,0.815199,0.005200,0.173496,0.009118,0.009871,...,NaN,NaN,NaN,0.005361,0.002396,0.004765,NaN,0.000682,0.002071,0.006504
111827,fd00d8117859ba1af8285ee43333f656b866431fe5805b...,2019-04-01,0.519803,0.358189,0.214206,0.026126,0.005388,0.703312,0.001189,0.382019,...,0.258989,0.009103,0.006135,0.002713,0.004676,0.003134,NaN,0.005985,0.006368,0.008868
111828,fee1f2692139fb8997dc59396938899536de641e391f91...,2019-04-01,0.313581,0.120557,0.335785,0.040861,0.002123,0.358962,0.000071,0.129342,...,NaN,NaN,NaN,0.001425,0.008921,0.007094,NaN,0.005616,0.001585,0.009621
111830,fdb5a10a0157795f0b2fc7ab448db65d101c057162e04d...,2019-04-01,0.347557,0.294794,0.264029,0.267828,0.005982,0.146199,0.387551,0.415000,...,NaN,NaN,NaN,1.004830,1.007076,0.938946,0.374851,1.007334,0.008624,0.100637
111832,fe171942b208185d4117da1dd35a521d7601a95f8ddd76...,2019-04-01,0.279415,0.713905,0.149532,0.052192,0.008365,0.714470,0.440893,0.379529,...,NaN,NaN,NaN,0.005371,0.000442,0.002237,NaN,0.004742,0.004684,0.000887
111835,fdf218df9e96f17ed9db918ff738155e22fa2b5023be1b...,2019-04-01,0.357590,0.003831,0.916256,0.029314,0.004213,0.209992,0.000172,1.056858,...,NaN,NaN,NaN,0.001147,0.001263,0.001131,NaN,0.009678,0.001531,0.008352

Wall time: 18min 37s

0

In [9]:
# https://www.kaggle.com/competitions/amex-default-prediction/discussion/328020
# https://www.kaggle.com/code/rohanrao/amex-competition-metric-implementations
class CB_Amex_Metric(object):
    def get_final_error(self, error, weight):
        return error
    def is_max_optimal(self):
        return True
    def evaluate(self, y_pred, y_true, weight):
        y_pred = y_pred[0]
        indices = np.argsort(y_pred)[::-1]
        preds, target = y_pred[indices], y_true[indices]
        weight = 20.0 - target * 19.0
        cum_norm_weight = (weight / weight.sum()).cumsum()
        four_pct_mask = cum_norm_weight <= 0.04
        d = np.sum(target[four_pct_mask]) / np.sum(target)
        weighted_target = target * weight
        lorentz = (weighted_target / weighted_target.sum()).cumsum()
        gini = ((lorentz - cum_norm_weight) * weight).sum()
        n_pos = np.sum(target)
        n_neg = target.shape[0] - n_pos
        gini_max = 10 * n_neg * (n_pos + 20 * n_neg - 19) / (n_pos + 20 * n_neg)
        g = gini / gini_max
        return 0.5 * (g + d), 0

In [ ]:
train = pd.read_csv('train.csv')
cat_features = ['B_30', 'B_31', 'B_38', 'D_114', 'D_116', 'D_117', 'D_120', 'D_126', 'D_63', 'D_64', 'D_66', 'D_68']
for c in cat_features: train[c] = train[c].astype(str)

x1, x2, y1, y2 = model_selection.train_test_split(train[col], train.target, test_size=0.20, random_state=22)
del train; gc.collect()
os.remove ('train.csv')

clf = CatBoostClassifier(iterations=1000, random_state=22, nan_mode='Min', eval_metric=CB_Amex_Metric())
clf.fit(x1, y1, eval_set=[(x2, y2)], cat_features=cat_features,  verbose=50)
preds = clf.predict_proba(x2)[:, 1]

In [ ]:
test = pd.read_csv('test.csv')
for c in cat_features: test[c] = test[c].astype(str)
test['prediction'] = clf.predict_proba(test[col])[:, 1]
sub2 = test[['customer_ID', 'prediction']]
del test;  gc.collect()
os.remove ('test.csv')

In [ ]:
sub2.columns = ['customer_ID', 'prediction2']
blend = pd.merge(sub1, sub2, how='inner', on='customer_ID')
blend.prediction = (blend.prediction * 0.955 + blend.prediction2 * 0.045)
blend[['customer_ID', 'prediction']].to_csv('submission.csv', index=False)