# exp18

下記のNotebookの特徴量抽出を目的

https://www.kaggle.com/code/yoshiki001/amex-lightgbm-baseline-exp6/data?scriptVersionId=101497304

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display
import datetime
import warnings
import gc
import random
import time
import pickle
import os

from sklearn.metrics import plot_confusion_matrix
from sklearn.model_selection import StratifiedKFold
from sklearn.calibration import CalibrationDisplay
# import optuna.integration.lightgbm as lgb
import lightgbm as lgb
# from lightgbm import LGBMClassifier, log_evaluation
from tqdm.auto import tqdm

from tsfresh import extract_features
from tsfresh.feature_extraction import ComprehensiveFCParameters
from tsfresh import select_features
from tsfresh.utilities.dataframe_functions import impute

from sklearn.model_selection import train_test_split

In [2]:
# kaggle = True
IS_COLAB = False

In [3]:
class CFG:
    EXPERIMENT = 14 #実験管理No.
    NUM_NEIGHBOR = 20
    SEED = 42
    THRESHOLD = 0.5
    n_splits = 5
    target = "point_of_interest"
    
    del_col_list = ["B_29"] #,"target"]
    
    features_avg = ['B_1', 'B_2', 'B_3', 'B_4', 'B_5', 'B_6', 'B_8', 'B_9', 'B_10', 'B_11', 'B_12', 'B_13', 'B_14', 'B_15', 
                    'B_16', 'B_17', 'B_18', 'B_19', 'B_20', 'B_21', 'B_22', 'B_23', 'B_24', 'B_25', 'B_28', 'B_30', 
                    'B_32', 'B_33', 'B_37', 'B_38', 'B_39', 'B_40', 'B_41', 'B_42', 'D_39', 'D_41', 'D_42', 'D_43', 'D_44', 
                    'D_45', 'D_46', 'D_47', 'D_48', 'D_50', 'D_51', 'D_53', 'D_54', 'D_55', 'D_58', 'D_59', 'D_60', 'D_61', 
                    'D_62', 'D_65', 'D_66', 'D_69', 'D_70', 'D_71', 'D_72', 'D_73', 'D_74', 'D_75', 'D_76', 'D_77', 'D_78', 
                    'D_80', 'D_82', 'D_84', 'D_86', 'D_91', 'D_92', 'D_94', 'D_96', 'D_103', 'D_104', 'D_108', 'D_112', 
                    'D_113', 'D_114', 'D_115', 'D_117', 'D_118', 'D_119', 'D_120', 'D_121', 'D_122', 'D_123', 'D_124', 
                    'D_125', 'D_126', 'D_128', 'D_129', 'D_131', 'D_132', 'D_133', 'D_134', 'D_135', 'D_136', 'D_140', 
                    'D_141', 'D_142', 'D_144', 'D_145', 'P_2', 'P_3', 'P_4', 'R_1', 'R_2', 'R_3', 'R_7', 'R_8', 'R_9', 
                    'R_10', 'R_11', 'R_14', 'R_15', 'R_16', 'R_17', 'R_20', 'R_21', 'R_22', 'R_24', 'R_26', 'R_27', 'S_3', 
                    'S_5', 'S_6', 'S_7', 'S_9', 'S_11', 'S_12', 'S_13', 'S_15', 'S_16', 'S_18', 'S_22', 'S_23', 'S_25', 'S_26']
    features_std = ['B_1', 'B_2', 'B_3', 'B_4', 'B_5', 'B_6', 'B_8', 'B_9', 'B_10', 'B_11', 'B_12', 'B_13', 'B_14', 'B_15', 
                    'B_16', 'B_17', 'B_18', 'B_19', 'B_20', 'B_21', 'B_22', 'B_23', 'B_24', 'B_25', 'B_28', 'B_30', 
                    'B_32', 'B_33', 'B_37', 'B_38', 'B_39', 'B_40', 'B_41', 'B_42', 'D_39', 'D_41', 'D_42', 'D_43', 'D_44', 
                    'D_45', 'D_46', 'D_47', 'D_48', 'D_50', 'D_51', 'D_53', 'D_54', 'D_55', 'D_58', 'D_59', 'D_60', 'D_61', 
                    'D_62', 'D_65', 'D_66', 'D_69', 'D_70', 'D_71', 'D_72', 'D_73', 'D_74', 'D_75', 'D_76', 'D_77', 'D_78', 
                    'D_80', 'D_82', 'D_84', 'D_86', 'D_91', 'D_92', 'D_94', 'D_96', 'D_103', 'D_104', 'D_108', 'D_112', 
                    'D_113', 'D_114', 'D_115', 'D_117', 'D_118', 'D_119', 'D_120', 'D_121', 'D_122', 'D_123', 'D_124', 
                    'D_125', 'D_126', 'D_128', 'D_129', 'D_131', 'D_132', 'D_133', 'D_134', 'D_135', 'D_136', 'D_140', 
                    'D_141', 'D_142', 'D_144', 'D_145', 'P_2', 'P_3', 'P_4', 'R_1', 'R_2', 'R_3', 'R_7', 'R_8', 'R_9', 
                    'R_10', 'R_11', 'R_14', 'R_15', 'R_16', 'R_17', 'R_20', 'R_21', 'R_22', 'R_24', 'R_26', 'R_27', 'S_3', 
                    'S_5', 'S_6', 'S_7', 'S_9', 'S_11', 'S_12', 'S_13', 'S_15', 'S_16', 'S_18', 'S_22', 'S_23', 'S_25', 'S_26']
    features_min = ['B_2', 'B_4', 'B_5', 'B_9', 'B_13', 'B_14', 'B_15', 'B_16', 'B_17', 'B_19', 'B_20', 'B_28', 'B_33', 
                    'B_36', 'B_42', 'D_39', 'D_41', 'D_42', 'D_45', 'D_46', 'D_48', 'D_50', 'D_51', 'D_53', 'D_55', 'D_56', 'D_58', 
                    'D_59', 'D_60', 'D_62', 'D_70', 'D_71', 'D_74', 'D_75', 'D_78', 'D_83', 'D_102', 'D_112', 'D_113', 'D_115', 
                    'D_118', 'D_119', 'D_121', 'D_122', 'D_128', 'D_132', 'D_140', 'D_141', 'D_144', 'D_145', 'P_2', 'P_3', 'R_1', 
                    'R_27', 'S_3', 'S_5', 'S_7', 'S_9', 'S_11', 'S_12', 'S_23', 'S_25']
    features_max = ['B_1', 'B_2', 'B_3', 'B_4', 'B_5', 'B_6', 'B_7', 'B_8', 'B_9', 'B_10', 'B_12', 'B_13', 'B_14', 'B_15', 'B_16', 
                    'B_17', 'B_18', 'B_19', 'B_21', 'B_23', 'B_24', 'B_25', 'B_30', 'B_33', 'B_37', 'B_38', 'B_39', 'B_40', 
                    'B_42', 'D_39', 'D_41', 'D_42', 'D_43', 'D_44', 'D_45', 'D_46', 'D_47', 'D_48', 'D_49', 'D_50', 'D_52', 'D_55', 
                    'D_56', 'D_58', 'D_59', 'D_60', 'D_61', 'D_63', 'D_64', 'D_65', 'D_70', 'D_71', 'D_72', 'D_73', 'D_74', 'D_76', 
                    'D_77', 'D_78', 'D_80', 'D_82', 'D_84', 'D_91', 'D_102', 'D_105', 'D_107', 'D_110', 'D_111', 'D_112', 'D_115', 
                    'D_116', 'D_117', 'D_118', 'D_119', 'D_121', 'D_122', 'D_123', 'D_124', 'D_125', 'D_126', 'D_128', 'D_131', 
                    'D_132', 'D_133', 'D_134', 'D_135', 'D_136', 'D_138', 'D_140', 'D_141', 'D_142', 'D_144', 'D_145', 'P_2', 'P_3', 
                    'P_4', 'R_1', 'R_3', 'R_5', 'R_6', 'R_7', 'R_8', 'R_10', 'R_11', 'R_14', 'R_17', 'R_20', 'R_26', 'R_27', 'S_3', 
                    'S_5', 'S_7', 'S_8', 'S_11', 'S_12', 'S_13', 'S_15', 'S_16', 'S_22', 'S_23', 'S_24', 'S_25', 'S_26', 'S_27']
    features_last = ['B_1', 'B_2', 'B_3', 'B_4', 'B_5', 'B_6', 'B_7', 'B_8', 'B_9', 'B_10', 'B_11', 'B_12', 'B_13', 'B_14', 'B_15', 
                     'B_16', 'B_17', 'B_18', 'B_19', 'B_20', 'B_21', 'B_22', 'B_23', 'B_24', 'B_25', 'B_26', 'B_28', 'B_30', 
                     'B_32', 'B_33', 'B_36', 'B_37', 'B_38', 'B_39', 'B_40', 'B_41', 'B_42', 'D_39', 'D_41', 'D_42', 'D_43', 'D_44', 
                     'D_45', 'D_46', 'D_47', 'D_48', 'D_49', 'D_50', 'D_51', 'D_52', 'D_53', 'D_54', 'D_55', 'D_56', 'D_58', 'D_59', 
                     'D_60', 'D_61', 'D_62', 'D_63', 'D_64', 'D_65', 'D_69', 'D_70', 'D_71', 'D_72', 'D_73', 'D_75', 'D_76', 'D_77', 
                     'D_78', 'D_79', 'D_80', 'D_81', 'D_82', 'D_83', 'D_86', 'D_91', 'D_96', 'D_105', 'D_106', 'D_112', 'D_114', 'D_119', 
                     'D_120', 'D_121', 'D_122', 'D_124', 'D_125', 'D_126', 'D_127', 'D_130', 'D_131', 'D_132', 'D_133', 'D_134', 'D_138', 
                     'D_140', 'D_141', 'D_142', 'D_145', 'P_2', 'P_3', 'P_4', 'R_1', 'R_2', 'R_3', 'R_4', 'R_5', 'R_6', 'R_7', 'R_8', 'R_9', 
                     'R_10', 'R_11', 'R_12', 'R_13', 'R_14', 'R_15', 'R_19', 'R_20', 'R_26', 'R_27', 'S_3', 'S_5', 'S_6', 'S_7', 'S_8', 'S_9', 
                     'S_11', 'S_12', 'S_13', 'S_16', 'S_19', 'S_20', 'S_22', 'S_23', 'S_24', 'S_25', 'S_26', 'S_27']
    


# Path setting

if IS_COLAB:
    data_dir = '../input/amex-default-prediction'
    save_dir = f'/content/drive/MyDrive/Kaggle/Amex-DefaultPrediction/exp/exp-{EXPERIMENT}'
    !mkdir -p {save_dir}
else:
    data_dir = '../input/amex-default-prediction'
    save_dir = './'

print(f"data_dir : {data_dir}")
print(f"save_dir : {save_dir}")
    
def seed_everything(seed):
    random.seed(seed)
    np.random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    
seed_everything(CFG.SEED)

data_dir : ../input/amex-default-prediction
save_dir : ./

In [4]:
def amex_metric(y_true: np.array, y_pred: np.array) -> float:

    # count of positives and negatives
    n_pos = y_true.sum()
    n_neg = y_true.shape[0] - n_pos

    # sorting by descring prediction values
    indices = np.argsort(y_pred)[::-1]
    preds, target = y_pred[indices], y_true[indices]

    # filter the top 4% by cumulative row weights
    weight = 20.0 - target * 19.0
    cum_norm_weight = (weight / weight.sum()).cumsum()
    four_pct_filter = cum_norm_weight <= 0.04

    # default rate captured at 4%
    d = target[four_pct_filter].sum() / n_pos

    # weighted gini coefficient
    lorentz = (target / n_pos).cumsum()
    gini = ((lorentz - cum_norm_weight) * weight).sum()

    # max weighted gini coefficient
    gini_max = 10 * n_neg * (1 - 19 / (n_pos + 20 * n_neg))

    # normalized weighted gini coefficient
    g = gini / gini_max

    return 0.5 * (g + d)

def lgb_amex_metric(y_true, y_pred):
    """The competition metric with lightgbm's calling convention"""
    return ('amex',
            amex_metric(y_true, y_pred),
            True)

In [5]:
def statistics(df,
               features_avg = CFG.features_avg,
               features_std = CFG.features_std,
               features_min = CFG.features_min,
               features_max = CFG.features_max,
               features_last = CFG.features_last):
    
    cid = pd.Categorical(df.pop('customer_ID'), ordered=True)
    last = (cid != np.roll(cid, -1)) # mask for last statement of every customer
    
    df_avg = (df
              .groupby(cid)
              .mean()[features_avg]
              .rename(columns={f: f"{f}_avg" for f in features_avg})
             )
    gc.collect()
    print('Computed avg')
    
    df_std = (df
              .groupby(cid)
              .mean()[features_std]
              .rename(columns={f: f"{f}_std" for f in features_std})
             )
    gc.collect()
    print('Computed std')
    
    df_min = (df
              .groupby(cid)
              .min()[features_min]
              .rename(columns={f: f"{f}_min" for f in features_min})
             )
    gc.collect()
    print('Computed min')
    
    df_max = (df
              .groupby(cid)
              .max()[features_max]
              .rename(columns={f: f"{f}_max" for f in features_max})
             )
    gc.collect()
    print('Computed max')
    
    df_last = (df.loc[last, features_last]
          .rename(columns={f: f"{f}_last" for f in features_last})
          .set_index(np.asarray(cid[last]))
         )
    gc.collect()
    print('Computed last')
    
    df = pd.concat([df_last, df_min, df_max, df_avg, df_std], axis=1)
    del df_last, df_avg, df_std, df_min, df_max, cid, last
    gc.collect
              
    return df

# data load

In [6]:
# start_time  = time.time()
df_train = pd.read_parquet(f'../input/AMEXdata-integerdtypes-parquetformat/train.parquet')
df_label = pd.read_csv(f'../input/amex-default-prediction/train_labels.csv')
# end_time  = time.time()
# print(f"read time：{int(end_time - start_time)}s")
print(df_train.shape)

KeyboardInterrupt:

In [7]:
# df_train.loc[2700014:, :]

In [8]:

# データを絞る
df_train2 = df_train.loc[2700015:, :]
df_train = df_train.loc[0:2700014, :]
# df_train2 = df_train.loc[319997:, :]

df_train.drop(columns = CFG.del_col_list,inplace = True)
df_train2.drop(columns = CFG.del_col_list,inplace = True)

print(f"df_train : {df_train.shape}")
display(df_train)
print(f"df_train2 : {df_train2.shape}")
display(df_train2)
print(f"df_label : {df_label.shape}")
display(df_label.head())

df_train : (2700015, 189)

,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
0,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-03-09,0.938469,0,0.008724,1.006838,0.009228,0.124035,0.0,0.004709,...,-1,-1,-1,0,0,0.0,NaN,0,0.000610,0
1,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-04-07,0.936665,0,0.004923,1.000653,0.006151,0.126750,0.0,0.002714,...,-1,-1,-1,0,0,0.0,NaN,0,0.005492,0
2,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-05-28,0.954180,3,0.021655,1.009672,0.006815,0.123977,0.0,0.009423,...,-1,-1,-1,0,0,0.0,NaN,0,0.006986,0
3,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-06-13,0.960384,0,0.013683,1.002700,0.001373,0.117169,0.0,0.005531,...,-1,-1,-1,0,0,0.0,NaN,0,0.006527,0
4,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-07-16,0.947248,0,0.015193,1.000727,0.007605,0.117325,0.0,0.009312,...,-1,-1,-1,0,0,0.0,NaN,0,0.008126,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2700010,7ca1addc5e1caa8dfe98e3f88a606734aed393728cc9c7...,2017-11-16,0.712959,0,0.004683,0.814162,0.004070,NaN,0.0,0.000792,...,-1,-1,-1,0,0,0.0,NaN,0,0.006212,0
2700011,7ca1addc5e1caa8dfe98e3f88a606734aed393728cc9c7...,2017-12-16,0.717567,0,0.002866,0.817167,0.004758,NaN,0.0,0.003424,...,-1,-1,-1,0,0,0.0,NaN,0,0.005307,0
2700012,7ca1addc5e1caa8dfe98e3f88a606734aed393728cc9c7...,2018-01-17,0.721974,0,0.001875,0.819956,0.008918,NaN,0.0,0.004029,...,-1,-1,-1,0,0,0.0,NaN,0,0.008508,0
2700013,7ca1addc5e1caa8dfe98e3f88a606734aed393728cc9c7...,2018-02-14,0.709065,0,0.009156,0.813486,0.003509,NaN,0.0,0.000635,...,-1,-1,-1,0,0,0.0,NaN,0,0.000701,0
2700014,7ca1addc5e1caa8dfe98e3f88a606734aed393728cc9c7...,2018-03-17,0.713721,0,0.007944,0.817886,0.009880,NaN,0.0,0.009914,...,-1,-1,-1,0,0,0.0,NaN,0,0.000488,0

df_train2 : (2831436, 189)

,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
2700015,7ca1ccd1234a5f18f5c9bdf843348e1b559261c5a7bdad...,2017-03-11,0.850266,0,0.000575,0.812974,0.005458,NaN,0.0,0.004501,...,-1,-1,-1,0,0,0.0,NaN,0,0.004787,0
2700016,7ca1ccd1234a5f18f5c9bdf843348e1b559261c5a7bdad...,2017-04-09,0.802441,0,0.005421,0.817911,0.509102,NaN,0.0,0.007012,...,-1,-1,-1,0,0,0.0,NaN,0,0.001837,0
2700017,7ca1ccd1234a5f18f5c9bdf843348e1b559261c5a7bdad...,2017-06-16,0.808068,0,0.004112,0.811541,0.004994,NaN,0.0,0.002847,...,-1,-1,-1,0,0,0.0,NaN,0,0.003195,0
2700018,7ca1ccd1234a5f18f5c9bdf843348e1b559261c5a7bdad...,2017-07-17,0.899655,0,0.009328,0.818695,0.001953,NaN,0.0,0.002305,...,-1,-1,-1,0,0,0.0,NaN,0,0.000980,0
2700019,7ca1ccd1234a5f18f5c9bdf843348e1b559261c5a7bdad...,2017-08-11,0.920872,0,0.044814,0.810695,0.008201,0.181002,0.0,0.007473,...,-1,-1,-1,0,0,0.0,NaN,0,0.009529,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5531446,fffff1d38b785cef84adeace64f8f83db3a0c31e8d92ea...,2017-11-05,0.979333,14,0.020818,0.828199,0.003487,0.090743,0.0,0.025139,...,-1,-1,-1,0,0,0.0,NaN,0,0.001498,0
5531447,fffff1d38b785cef84adeace64f8f83db3a0c31e8d92ea...,2017-12-23,0.984907,10,0.007209,0.812610,0.005904,0.079886,0.0,0.023691,...,-1,-1,-1,0,0,0.0,NaN,0,0.008225,0
5531448,fffff1d38b785cef84adeace64f8f83db3a0c31e8d92ea...,2018-01-06,0.983019,15,0.013151,0.815422,0.003457,0.100503,0.0,0.012343,...,-1,-1,-1,0,0,0.0,NaN,0,0.006773,0
5531449,fffff1d38b785cef84adeace64f8f83db3a0c31e8d92ea...,2018-02-06,0.969861,15,0.009855,1.003541,0.005117,0.101802,0.0,0.008578,...,-1,-1,-1,0,0,0.0,NaN,0,0.001168,0
5531450,fffff1d38b785cef84adeace64f8f83db3a0c31e8d92ea...,2018-03-14,0.982175,0,0.000077,0.992880,0.000809,0.119165,0.0,0.014092,...,-1,-1,-1,0,0,0.0,NaN,0,0.003184,0

df_label : (458913, 2)

                                         customer_ID  target
0  0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...       0
1  00000fd6641609c6ece5454664794f0340ad84dddce9a2...       0
2  00001b22f846c82c51f6e3958ccd81970162bae8b007e8...       0
3  000041bdba6ecadd89a52d11886e8eaaec9325906c9723...       0
4  00007889e4fcd2614b6cbe7f8f3d2e5c728eca32d9eb8a...       0

# tsfresh で特徴量作成

In [9]:
#時系列特徴量を作成
fc_parameters = {
#     'partial_autocorrelation': [{'lag': 1},{'lag': 3}, {'lag': 5}, {'lag': 7}, {'lag': 9}],
    "autocorrelation": [{'lag': 1}, {'lag': 3}, {'lag': 5}, {'lag': 7}, {'lag': 12}],
}

df_ts = df_train.copy()
df_ts = df_ts.fillna(0)
df_ts = extract_features(df_ts, column_id="customer_ID", column_sort="S_2", default_fc_parameters=fc_parameters)

#列名変更
col_list = list(df_ts)
print(len(col_list))
for idx in tqdm(range(len(col_list))):
    col_tmp = col_list[idx].replace('"','')
    df_ts = df_ts.rename(columns={col_list[idx]:col_tmp})
    

df_ts.reset_index(inplace = True)
df_ts = df_ts.rename(columns = {"index":"customer_ID"})
print(df_ts.shape)
df_ts.head()

Feature Extraction: 100%|██████████| 40/40 [58:37<00:00, 87.93s/it]

935

  0%|          | 0/935 [00:00<?, ?it/s]

(223920, 936)

,customer_ID,P_2__autocorrelation__lag_1,P_2__autocorrelation__lag_3,P_2__autocorrelation__lag_5,P_2__autocorrelation__lag_7,P_2__autocorrelation__lag_12,D_39__autocorrelation__lag_1,D_39__autocorrelation__lag_3,D_39__autocorrelation__lag_5,D_39__autocorrelation__lag_7,...,D_144__autocorrelation__lag_1,D_144__autocorrelation__lag_3,D_144__autocorrelation__lag_5,D_144__autocorrelation__lag_7,D_144__autocorrelation__lag_12,D_145__autocorrelation__lag_1,D_145__autocorrelation__lag_3,D_145__autocorrelation__lag_5,D_145__autocorrelation__lag_7,D_145__autocorrelation__lag_12
0,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,0.174903,0.101935,-0.236118,-0.600763,0.007917,-0.097222,-0.025000,-0.052083,-0.097222,...,-0.104158,-0.052005,0.381391,-0.376558,1.735089,NaN,NaN,NaN,NaN,NaN
1,00000fd6641609c6ece5454664794f0340ad84dddce9a2...,0.687463,0.331069,-0.120334,-0.555145,-1.252227,-0.110304,-0.429165,-0.343036,0.388145,...,-0.232295,0.127100,-0.118868,0.054102,0.577802,NaN,NaN,NaN,NaN,NaN
2,00001b22f846c82c51f6e3958ccd81970162bae8b007e8...,-0.088271,-0.081983,0.421744,-0.314059,-0.005768,NaN,NaN,NaN,NaN,...,-0.171315,-0.046841,0.354531,-0.548845,0.831806,NaN,NaN,NaN,NaN,NaN
3,000041bdba6ecadd89a52d11886e8eaaec9325906c9723...,0.790905,0.430614,-0.090225,-0.731281,-1.926653,0.016960,0.163592,-0.094806,-0.150117,...,-0.079493,-0.340753,0.441229,-0.033458,-0.352436,NaN,NaN,NaN,NaN,NaN
4,00007889e4fcd2614b6cbe7f8f3d2e5c728eca32d9eb8a...,0.469236,0.105873,-0.511452,-0.262360,-0.540190,NaN,NaN,NaN,NaN,...,-0.134475,0.082192,0.284313,-0.272151,-0.205607,NaN,NaN,NaN,NaN,NaN

In [10]:
df_ts.to_pickle("../output/exp18_tsfresh/train_autocorr_1.pkl")

del df_ts,df_train
gc.collect

In [11]:
#時系列特徴量を作成
fc_parameters = {
#     'partial_autocorrelation': [{'lag': 1},{'lag': 3}, {'lag': 5}, {'lag': 7}, {'lag': 9}],
    "autocorrelation": [{'lag': 1}, {'lag': 3}, {'lag': 5}, {'lag': 7}, {'lag': 12}],
}

df_ts2 = df_train2.copy()
df_ts2 = df_ts2.fillna(0)
df_ts2 = extract_features(df_ts2, column_id="customer_ID", column_sort="S_2", default_fc_parameters=fc_parameters)

#列名変更
col_list = list(df_ts2)
print(len(col_list))
for idx in tqdm(range(len(col_list))):
    col_tmp = col_list[idx].replace('"','')
    df_ts2 = df_ts2.rename(columns={col_list[idx]:col_tmp})
    

df_ts2.reset_index(inplace = True)
df_ts2 = df_ts2.rename(columns = {"index":"customer_ID"})
print(df_ts2.shape)
df_ts2.head()

Feature Extraction: 100%|██████████| 40/40 [1:01:13<00:00, 91.83s/it]

935

  0%|          | 0/935 [00:00<?, ?it/s]

(234993, 936)

,customer_ID,P_2__autocorrelation__lag_1,P_2__autocorrelation__lag_3,P_2__autocorrelation__lag_5,P_2__autocorrelation__lag_7,P_2__autocorrelation__lag_12,D_39__autocorrelation__lag_1,D_39__autocorrelation__lag_3,D_39__autocorrelation__lag_5,D_39__autocorrelation__lag_7,...,D_144__autocorrelation__lag_1,D_144__autocorrelation__lag_3,D_144__autocorrelation__lag_5,D_144__autocorrelation__lag_7,D_144__autocorrelation__lag_12,D_145__autocorrelation__lag_1,D_145__autocorrelation__lag_3,D_145__autocorrelation__lag_5,D_145__autocorrelation__lag_7,D_145__autocorrelation__lag_12
0,7ca1ccd1234a5f18f5c9bdf843348e1b559261c5a7bdad...,0.293378,-0.107991,-0.123683,0.249804,NaN,0.185742,-0.210056,-0.391965,0.152930,...,-0.334135,-0.316653,0.354726,0.656556,NaN,NaN,NaN,NaN,NaN,NaN
1,7ca1f9f7732cf988864ba28fae198f46680e30eda87681...,0.259775,-0.056339,-0.688747,0.074679,NaN,-0.052833,0.323457,-0.300054,-0.355878,...,0.262173,0.305087,-1.129348,-0.055914,NaN,NaN,NaN,NaN,NaN,NaN
2,7ca1fdc286b54e698886f473e1d020674c94c16f68ac88...,0.790729,0.243015,-0.436973,-0.802342,0.605706,NaN,NaN,NaN,NaN,...,-0.353629,0.240823,-0.046169,-0.158410,1.637485,NaN,NaN,NaN,NaN,NaN
3,7ca2713ea23116fc72afde132b868c678c79ff152310a9...,0.435083,-0.512346,-0.091732,0.044622,0.394476,NaN,NaN,NaN,NaN,...,-0.059136,0.025750,-0.005781,-0.203850,-0.453656,NaN,NaN,NaN,NaN,NaN
4,7ca27fba28a327aad042af4879fc1d9e62c0e4ca087905...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.000000,NaN,NaN,NaN,NaN,-1.0,NaN,NaN,NaN,NaN

In [12]:
df_ts2.to_pickle("../output/exp18_tsfresh/train_autocorr_2.pkl")

del df_ts2,df_train2
gc.collect

In [ ]:
train_ts = pd.concat([df_ts,df_ts2],axis =0)
pd.concat([df_ts,df_ts2],axis =0)["customer_ID"].value_counts()

In [ ]:
df_ts = pd.merge(df_ts,df_label,how = "left",on = "customer_ID")
df_ts = df_ts.fillna(0)
df_ts.head()

features_ts = df_ts.columns.values.tolist()
del features_ts[0]
del features_ts[-1]

In [ ]:
impute(df_ts[features_ts])
features_filtered = select_features(df_ts[features_ts], df_ts["target"])


df_ts = pd.concat([df_ts["customer_ID"],features_filtered], axis=1) 
df_ts.head()

In [ ]:
df_ts.to_pickle("../output/exp18_tsfresh/train_autocorrelation.pkl")

del df_ts

# test data

In [6]:
# start_time  = time.time()
df_test = pd.read_parquet(f'../input/AMEXdata-integerdtypes-parquetformat/test.parquet')
# df_label = pd.read_csv(f'../input/amex-default-prediction/train_labels.csv')
# end_time  = time.time()
# print(f"read time：{int(end_time - start_time)}s")
print(df_test.shape)

(11363762, 190)

In [17]:

# データを絞る
df_test5 = df_test.loc[9999998:, :]
df_test4 = df_test.loc[7500003 : 9999997, :]
df_test3 = df_test.loc[5000000 : 7500002, :]
df_test2 = df_test.loc[2500002 : 4999999, :]
df_test = df_test.loc[:2500001, :]
# df_train2 = df_train.loc[319997:, :]

df_test5.drop(columns = CFG.del_col_list,inplace = True)
df_test4.drop(columns = CFG.del_col_list,inplace = True)
df_test3.drop(columns = CFG.del_col_list,inplace = True)
df_test2.drop(columns = CFG.del_col_list,inplace = True)
df_test.drop(columns = CFG.del_col_list,inplace = True)

print(f"df_train5 : {df_test5.shape}")
display(df_test4)
print(f"df_train4 : {df_test4.shape}")
display(df_test4)
print(f"df_train3 : {df_test3.shape}")
display(df_test3)
print(f"df_train2 : {df_test2.shape}")
display(df_test2)
print(f"df_train2 : {df_test.shape}")
display(df_test)
# print(f"df_label : {df_label.shape}")
# display(df_label.head())

df_train5 : (1363764, 189)

,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
7500003,a92350cf849d1eff38de58b7daca20382e5c1a0d6bc864...,2018-04-08,0.985366,5,0.007158,1.001707,0.0,0.316445,0.0,0.009691,...,-1,-1,-1,0,0,0.0,NaN,0,0.004370,0
7500004,a92350cf849d1eff38de58b7daca20382e5c1a0d6bc864...,2018-05-20,1.007298,17,0.008129,1.005833,0.0,0.393961,0.0,0.001984,...,-1,-1,-1,0,0,0.0,NaN,0,0.009266,0
7500005,a92350cf849d1eff38de58b7daca20382e5c1a0d6bc864...,2018-06-04,1.003686,1,0.009860,1.008711,0.0,0.351321,0.0,0.002403,...,-1,-1,-1,0,0,0.0,NaN,0,0.005268,0
7500006,a92350cf849d1eff38de58b7daca20382e5c1a0d6bc864...,2018-07-06,1.003790,0,0.005601,1.007824,0.0,0.226581,0.0,0.002702,...,-1,-1,-1,0,0,0.0,NaN,0,0.002305,0
7500007,a92350cf849d1eff38de58b7daca20382e5c1a0d6bc864...,2018-08-29,1.009338,0,0.021354,0.812808,0.0,0.391542,0.0,0.009827,...,-1,-1,-1,0,0,0.0,NaN,0,0.004868,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999993,e14ac21bb0b97ccb4193fb0435c4615843073aec7e6ae9...,2019-06-26,0.357187,0,0.104616,0.043538,0.0,0.281272,0.0,0.480418,...,1,0,0,0,0,0.0,NaN,0,0.001001,0
9999994,e14ac21bb0b97ccb4193fb0435c4615843073aec7e6ae9...,2019-07-26,0.310747,0,0.116666,0.041063,0.0,0.269000,0.0,0.527927,...,1,0,0,0,0,0.0,NaN,0,0.006740,0
9999995,e14ac21bb0b97ccb4193fb0435c4615843073aec7e6ae9...,2019-08-03,0.309222,1,0.116648,0.031682,0.0,0.267444,0.0,0.571912,...,1,0,0,0,0,0.0,NaN,0,0.006274,0
9999996,e14ac21bb0b97ccb4193fb0435c4615843073aec7e6ae9...,2019-09-03,0.297141,1,0.112059,0.034442,0.0,0.256061,0.0,0.590250,...,1,0,0,0,0,0.0,NaN,0,0.009179,0
9999997,e14ac21bb0b97ccb4193fb0435c4615843073aec7e6ae9...,2019-10-04,0.326546,2,0.105429,0.046723,0.0,0.248995,0.0,0.588499,...,1,0,0,0,0,0.0,NaN,0,0.001442,0

df_train4 : (2499995, 189)

,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
7500003,a92350cf849d1eff38de58b7daca20382e5c1a0d6bc864...,2018-04-08,0.985366,5,0.007158,1.001707,0.0,0.316445,0.0,0.009691,...,-1,-1,-1,0,0,0.0,NaN,0,0.004370,0
7500004,a92350cf849d1eff38de58b7daca20382e5c1a0d6bc864...,2018-05-20,1.007298,17,0.008129,1.005833,0.0,0.393961,0.0,0.001984,...,-1,-1,-1,0,0,0.0,NaN,0,0.009266,0
7500005,a92350cf849d1eff38de58b7daca20382e5c1a0d6bc864...,2018-06-04,1.003686,1,0.009860,1.008711,0.0,0.351321,0.0,0.002403,...,-1,-1,-1,0,0,0.0,NaN,0,0.005268,0
7500006,a92350cf849d1eff38de58b7daca20382e5c1a0d6bc864...,2018-07-06,1.003790,0,0.005601,1.007824,0.0,0.226581,0.0,0.002702,...,-1,-1,-1,0,0,0.0,NaN,0,0.002305,0
7500007,a92350cf849d1eff38de58b7daca20382e5c1a0d6bc864...,2018-08-29,1.009338,0,0.021354,0.812808,0.0,0.391542,0.0,0.009827,...,-1,-1,-1,0,0,0.0,NaN,0,0.004868,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999993,e14ac21bb0b97ccb4193fb0435c4615843073aec7e6ae9...,2019-06-26,0.357187,0,0.104616,0.043538,0.0,0.281272,0.0,0.480418,...,1,0,0,0,0,0.0,NaN,0,0.001001,0
9999994,e14ac21bb0b97ccb4193fb0435c4615843073aec7e6ae9...,2019-07-26,0.310747,0,0.116666,0.041063,0.0,0.269000,0.0,0.527927,...,1,0,0,0,0,0.0,NaN,0,0.006740,0
9999995,e14ac21bb0b97ccb4193fb0435c4615843073aec7e6ae9...,2019-08-03,0.309222,1,0.116648,0.031682,0.0,0.267444,0.0,0.571912,...,1,0,0,0,0,0.0,NaN,0,0.006274,0
9999996,e14ac21bb0b97ccb4193fb0435c4615843073aec7e6ae9...,2019-09-03,0.297141,1,0.112059,0.034442,0.0,0.256061,0.0,0.590250,...,1,0,0,0,0,0.0,NaN,0,0.009179,0
9999997,e14ac21bb0b97ccb4193fb0435c4615843073aec7e6ae9...,2019-10-04,0.326546,2,0.105429,0.046723,0.0,0.248995,0.0,0.588499,...,1,0,0,0,0,0.0,NaN,0,0.001442,0

df_train3 : (2500003, 189)

,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
5000000,70d674d677597d9e55c8cb55aab0002227aca0a0ef8ce2...,2018-04-04,0.566768,0,0.034163,0.041908,0.000000,0.465069,0.0,0.184980,...,-1,-1,-1,0,0,0.0,NaN,0,0.001998,0
5000001,70d674d677597d9e55c8cb55aab0002227aca0a0ef8ce2...,2018-05-29,0.608150,11,0.029739,1.006454,0.000000,0.390930,0.0,0.094531,...,-1,-1,-1,0,0,0.0,NaN,0,0.004276,0
5000002,70d674d677597d9e55c8cb55aab0002227aca0a0ef8ce2...,2018-06-15,0.602489,0,0.016772,1.009704,0.000000,0.474383,0.0,0.096191,...,-1,-1,-1,0,0,0.0,NaN,0,0.006239,0
5000003,70d674d677597d9e55c8cb55aab0002227aca0a0ef8ce2...,2018-07-07,0.616244,0,0.085724,1.009494,0.501725,0.422897,0.0,0.043950,...,-1,-1,-1,0,0,0.0,NaN,0,0.005193,0
5000004,70d674d677597d9e55c8cb55aab0002227aca0a0ef8ce2...,2018-08-21,0.578073,2,0.136684,0.060115,0.000000,0.280499,0.0,0.135395,...,-1,-1,-1,0,0,0.0,NaN,0,0.008117,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7499998,a923447a24ce27c56242f2b2f34efb6c4ad255d13ff83c...,2019-06-25,0.810865,0,0.003215,0.810805,0.000000,NaN,0.0,0.006914,...,-1,-1,-1,0,0,0.0,NaN,0,0.004122,0
7499999,a923447a24ce27c56242f2b2f34efb6c4ad255d13ff83c...,2019-07-26,0.790908,0,0.003403,0.815363,0.000000,NaN,0.0,0.001508,...,-1,-1,-1,0,0,0.0,NaN,0,0.001042,0
7500000,a923447a24ce27c56242f2b2f34efb6c4ad255d13ff83c...,2019-08-26,0.868917,0,0.001352,0.813355,0.000000,NaN,0.0,0.005854,...,-1,-1,-1,0,0,0.0,NaN,0,0.000647,0
7500001,a923447a24ce27c56242f2b2f34efb6c4ad255d13ff83c...,2019-09-25,0.885961,0,0.003163,0.816380,0.000000,NaN,0.0,0.001945,...,-1,-1,-1,0,0,0.0,NaN,0,0.004960,0
7500002,a923447a24ce27c56242f2b2f34efb6c4ad255d13ff83c...,2019-10-26,0.887531,0,0.003258,0.819530,0.000000,NaN,0.0,0.000277,...,-1,-1,-1,0,0,0.0,NaN,0,0.005423,0

df_train2 : (2499998, 189)

,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
2500002,38514358af669399baf0652e355080ba0d8a628744d960...,2019-06-23,0.532974,0,0.081847,0.816668,0.000000,0.064479,0.0,0.006827,...,-1,-1,-1,-1,0,NaN,NaN,-1,0.006867,-1
2500003,38514358af669399baf0652e355080ba0d8a628744d960...,2019-07-07,0.535875,0,0.084695,0.819049,0.000000,0.099205,0.0,0.008215,...,-1,-1,-1,0,0,0.0,NaN,0,0.002033,0
2500004,38514358af669399baf0652e355080ba0d8a628744d960...,2019-08-13,0.438828,0,0.007379,0.811977,0.000000,0.102787,0.0,0.014641,...,-1,-1,-1,0,0,0.0,NaN,0,0.005600,0
2500005,38514358af669399baf0652e355080ba0d8a628744d960...,2019-09-12,0.512089,0,0.008148,0.815859,0.000000,0.101046,0.0,0.009306,...,-1,-1,-1,0,0,0.0,NaN,0,0.005992,0
2500006,38514358af669399baf0652e355080ba0d8a628744d960...,2019-10-12,0.530655,0,0.008791,0.814470,0.000000,0.102028,0.0,0.011383,...,-1,-1,-1,0,0,0.0,NaN,0,0.008917,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4999995,70d673ec90b75bc1bf950f4efaaa60528176064b2d11e7...,2019-06-10,0.293495,0,0.224331,0.060661,0.000000,0.109669,0.0,0.200834,...,-1,-1,-1,0,0,0.0,NaN,0,0.008131,0
4999996,70d673ec90b75bc1bf950f4efaaa60528176064b2d11e7...,2019-07-19,0.346996,1,0.210171,0.069815,0.502551,0.136359,0.0,0.210749,...,-1,-1,-1,0,0,0.0,NaN,0,0.009408,0
4999997,70d673ec90b75bc1bf950f4efaaa60528176064b2d11e7...,2019-08-14,0.240100,0,0.213184,0.063851,0.000000,0.155052,0.0,0.216380,...,-1,-1,-1,0,0,0.0,NaN,0,0.005168,0
4999998,70d673ec90b75bc1bf950f4efaaa60528176064b2d11e7...,2019-09-05,0.198588,18,0.220979,0.068843,0.000000,0.149107,0.0,0.217524,...,-1,-1,-1,0,0,0.0,NaN,0,0.003319,0
4999999,70d673ec90b75bc1bf950f4efaaa60528176064b2d11e7...,2019-10-27,0.217395,9,0.213057,0.062920,0.000000,0.142393,0.0,0.212520,...,-1,-1,-1,0,0,0.0,NaN,0,0.007224,0

df_train2 : (2500002, 189)

,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
0,00000469ba478561f23a92a868bd366de6f6527a684c9a...,2019-02-19,0.631315,0,0.010728,0.814497,0.0,0.168651,0.0,0.002347,...,-1,-1,-1,-1,0,NaN,NaN,-1,0.008281,-1
1,00000469ba478561f23a92a868bd366de6f6527a684c9a...,2019-03-25,0.587042,0,0.011026,0.810848,0.0,0.241389,0.0,0.009132,...,-1,-1,-1,0,0,0.0,NaN,0,0.003753,0
2,00000469ba478561f23a92a868bd366de6f6527a684c9a...,2019-04-25,0.609056,0,0.016390,1.004620,0.0,0.266976,0.0,0.004192,...,-1,-1,-1,0,0,0.0,NaN,0,0.002156,0
3,00000469ba478561f23a92a868bd366de6f6527a684c9a...,2019-05-20,0.614911,0,0.021672,0.816549,0.0,0.188947,0.0,0.015325,...,-1,-1,-1,0,0,0.0,NaN,0,0.005206,0
4,00000469ba478561f23a92a868bd366de6f6527a684c9a...,2019-06-15,0.591673,8,0.015923,0.810456,0.0,0.180035,0.0,0.011281,...,-1,-1,-1,0,0,0.0,NaN,0,0.007421,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2499997,3851266cfc0a974ccf29997be935c0a5b7cb1538d37d7b...,2018-12-28,0.812666,0,0.000104,1.007815,0.0,0.094655,0.0,0.009765,...,-1,-1,-1,0,0,0.0,NaN,0,0.002460,0
2499998,3851266cfc0a974ccf29997be935c0a5b7cb1538d37d7b...,2019-01-28,0.816549,0,0.003709,0.818114,0.0,0.092956,0.0,0.003661,...,-1,-1,-1,0,0,0.0,NaN,0,0.009596,0
2499999,3851266cfc0a974ccf29997be935c0a5b7cb1538d37d7b...,2019-02-26,0.811029,2,0.009752,0.816586,0.0,0.088762,0.0,0.005129,...,-1,-1,-1,0,0,0.0,NaN,0,0.007116,0
2500000,3851266cfc0a974ccf29997be935c0a5b7cb1538d37d7b...,2019-03-31,0.820946,0,0.001185,1.003419,0.0,0.088188,0.0,0.002681,...,-1,-1,-1,0,0,0.0,NaN,0,0.003587,0
2500001,3851266cfc0a974ccf29997be935c0a5b7cb1538d37d7b...,2019-04-27,0.823362,0,0.006275,0.812474,0.0,0.130493,0.0,0.005419,...,-1,-1,-1,0,0,0.0,NaN,0,0.002294,0

# tsfresh で特徴量作成

In [18]:
#時系列特徴量を作成
fc_parameters = {
#     'partial_autocorrelation': [{'lag': 1},{'lag': 3}, {'lag': 5}, {'lag': 7}, {'lag': 9}],
    "autocorrelation": [{'lag': 1}, {'lag': 3}, {'lag': 5}, {'lag': 7}, {'lag': 12}],
}

df_ts = df_test.copy()
df_ts = df_ts.fillna(0)
df_ts = extract_features(df_ts, column_id="customer_ID", column_sort="S_2", default_fc_parameters=fc_parameters)

#列名変更
col_list = list(df_ts)
print(len(col_list))
for idx in tqdm(range(len(col_list))):
    col_tmp = col_list[idx].replace('"','')
    df_ts = df_ts.rename(columns={col_list[idx]:col_tmp})
    

df_ts.reset_index(inplace = True)
df_ts = df_ts.rename(columns = {"index":"customer_ID"})
print(df_ts.shape)
df_ts.head()

Feature Extraction: 100%|██████████| 40/40 [49:40<00:00, 74.52s/it]

935

  0%|          | 0/935 [00:00<?, ?it/s]

(203365, 936)

,customer_ID,P_2__autocorrelation__lag_1,P_2__autocorrelation__lag_3,P_2__autocorrelation__lag_5,P_2__autocorrelation__lag_7,P_2__autocorrelation__lag_12,D_39__autocorrelation__lag_1,D_39__autocorrelation__lag_3,D_39__autocorrelation__lag_5,D_39__autocorrelation__lag_7,...,D_144__autocorrelation__lag_1,D_144__autocorrelation__lag_3,D_144__autocorrelation__lag_5,D_144__autocorrelation__lag_7,D_144__autocorrelation__lag_12,D_145__autocorrelation__lag_1,D_145__autocorrelation__lag_3,D_145__autocorrelation__lag_5,D_145__autocorrelation__lag_7,D_145__autocorrelation__lag_12
0,00000469ba478561f23a92a868bd366de6f6527a684c9a...,-0.249195,0.575117,-0.846765,0.464349,NaN,-0.457589,-0.491071,-0.156250,0.044643,...,0.229949,-0.872252,0.549402,0.395598,NaN,-0.015625,-0.0625,-0.15625,-0.4375,NaN
1,00001bf2e77ff879fab36aa4fac689b9ba411dae63ae39...,-0.009730,0.112103,0.000943,0.035518,-0.736948,-0.083553,-0.343363,-0.081074,-0.552553,...,-0.213817,0.207717,0.268264,-0.139059,-1.751158,NaN,NaN,NaN,NaN,NaN
2,0000210045da4f81e5f122c6bde5c2a617d03eef67f82c...,0.738738,-0.255762,-0.809345,-0.101577,-0.373567,-0.018947,-0.417284,0.075231,0.376715,...,0.776741,0.408232,-0.008703,-0.590403,-2.749268,NaN,NaN,NaN,NaN,NaN
3,00003b41e58ede33b8daf61ab56d9952f17c9ad1c3976c...,0.282905,0.175757,-0.071650,-0.527076,1.976086,-0.091610,0.451081,-0.502069,0.166779,...,0.824306,0.335326,-0.409178,-0.760731,-0.946806,NaN,NaN,NaN,NaN,NaN
4,00004b22eaeeeb0ec976890c1d9bfc14fd9427e98c4ee9...,0.491735,-0.247946,0.058991,-0.198007,1.146514,-0.488512,-0.351867,0.128213,0.223028,...,0.167526,-0.370083,0.275548,0.417013,0.952919,NaN,NaN,NaN,NaN,NaN

In [19]:
# df_ts.to_pickle("../output/exp18_tsfresh/train_partial_autocorrelation.pkl")
df_ts.to_pickle("../output/exp18_tsfresh/test_autocorr_1.pkl")

del df_ts,df_test
gc.collect

In [20]:
#時系列特徴量を作成
fc_parameters = {
#     'partial_autocorrelation': [{'lag': 1},{'lag': 3}, {'lag': 5}, {'lag': 7}, {'lag': 9}],
    "autocorrelation": [{'lag': 1}, {'lag': 3}, {'lag': 5}, {'lag': 7}, {'lag': 12}],
}

df_ts = df_test2.copy()
df_ts = df_ts.fillna(0)
df_ts = extract_features(df_ts, column_id="customer_ID", column_sort="S_2", default_fc_parameters=fc_parameters)

#列名変更
col_list = list(df_ts)
print(len(col_list))
for idx in tqdm(range(len(col_list))):
    col_tmp = col_list[idx].replace('"','')
    df_ts = df_ts.rename(columns={col_list[idx]:col_tmp})
    

df_ts.reset_index(inplace = True)
df_ts = df_ts.rename(columns = {"index":"customer_ID"})
print(df_ts.shape)
df_ts.head()

Feature Extraction: 100%|██████████| 40/40 [52:16<00:00, 78.42s/it]

935

  0%|          | 0/935 [00:00<?, ?it/s]

(203446, 936)

,customer_ID,P_2__autocorrelation__lag_1,P_2__autocorrelation__lag_3,P_2__autocorrelation__lag_5,P_2__autocorrelation__lag_7,P_2__autocorrelation__lag_12,D_39__autocorrelation__lag_1,D_39__autocorrelation__lag_3,D_39__autocorrelation__lag_5,D_39__autocorrelation__lag_7,...,D_144__autocorrelation__lag_1,D_144__autocorrelation__lag_3,D_144__autocorrelation__lag_5,D_144__autocorrelation__lag_7,D_144__autocorrelation__lag_12,D_145__autocorrelation__lag_1,D_145__autocorrelation__lag_3,D_145__autocorrelation__lag_5,D_145__autocorrelation__lag_7,D_145__autocorrelation__lag_12
0,38514358af669399baf0652e355080ba0d8a628744d960...,-0.251927,0.215290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.119766,-1.153208,NaN,NaN,NaN,-0.0625,-0.375,NaN,NaN,NaN
1,385143d286085def3391a553393424b6bd9817ff057c88...,0.385190,-0.138741,-0.489741,-0.050005,-0.118281,0.019473,-0.276410,-0.210678,0.918710,...,-0.027747,-0.011846,-0.039398,-0.198412,1.170328,NaN,NaN,NaN,NaN,NaN
2,385173f4ae36360b510d09ddaef3a45c3d5660a5482098...,0.247492,-0.140395,-0.330070,-0.593186,0.777880,0.090753,-0.287671,-0.154110,-0.287671,...,-0.418167,0.079393,-0.431906,0.343319,-1.077001,NaN,NaN,NaN,NaN,NaN
3,38517c7042b4d4a3dcd2950f4b0947957c3aa59ecba6de...,-0.254789,0.041928,-0.150441,-0.038804,0.174942,0.635502,-0.219539,-0.814403,-0.305093,...,0.120961,-0.417231,-0.331881,0.625876,-1.957814,NaN,NaN,NaN,NaN,NaN
4,38519f5dd5b37a8570c23ce8da412b4a44f9fb97c40e79...,-0.006892,-0.165526,-0.134898,-0.175408,-1.298278,-0.693827,-0.259479,-0.299225,-0.331870,...,-0.245536,-0.367842,0.488299,-0.036785,-1.179812,NaN,NaN,NaN,NaN,NaN

In [21]:
df_ts.to_pickle("../output/exp18_tsfresh/test_autocorr_2.pkl")

del df_ts,df_test2
gc.collect

In [22]:
#時系列特徴量を作成
fc_parameters = {
#     'partial_autocorrelation': [{'lag': 1},{'lag': 3}, {'lag': 5}, {'lag': 7}, {'lag': 9}],
    "autocorrelation": [{'lag': 1}, {'lag': 3}, {'lag': 5}, {'lag': 7}, {'lag': 12}],
}

df_ts = df_test3.copy()
df_ts = df_ts.fillna(0)
df_ts = extract_features(df_ts, column_id="customer_ID", column_sort="S_2", default_fc_parameters=fc_parameters)

#列名変更
col_list = list(df_ts)
print(len(col_list))
for idx in tqdm(range(len(col_list))):
    col_tmp = col_list[idx].replace('"','')
    df_ts = df_ts.rename(columns={col_list[idx]:col_tmp})
    

df_ts.reset_index(inplace = True)
df_ts = df_ts.rename(columns = {"index":"customer_ID"})
print(df_ts.shape)
df_ts.head()

Feature Extraction: 100%|██████████| 40/40 [52:17<00:00, 78.43s/it]

935

  0%|          | 0/935 [00:00<?, ?it/s]

(203389, 936)

,customer_ID,P_2__autocorrelation__lag_1,P_2__autocorrelation__lag_3,P_2__autocorrelation__lag_5,P_2__autocorrelation__lag_7,P_2__autocorrelation__lag_12,D_39__autocorrelation__lag_1,D_39__autocorrelation__lag_3,D_39__autocorrelation__lag_5,D_39__autocorrelation__lag_7,...,D_144__autocorrelation__lag_1,D_144__autocorrelation__lag_3,D_144__autocorrelation__lag_5,D_144__autocorrelation__lag_7,D_144__autocorrelation__lag_12,D_145__autocorrelation__lag_1,D_145__autocorrelation__lag_3,D_145__autocorrelation__lag_5,D_145__autocorrelation__lag_7,D_145__autocorrelation__lag_12
0,70d674d677597d9e55c8cb55aab0002227aca0a0ef8ce2...,0.182324,0.086954,-0.297808,-0.393470,1.027541,-0.158576,0.179196,0.060420,-0.137540,...,-0.357961,-0.553319,0.228848,-0.268770,-1.617482,NaN,NaN,NaN,NaN,NaN
1,70d679565ec4eed960ef882af0b01185359ad0081fd01a...,0.823044,0.361448,-0.148559,-0.808331,-1.574271,NaN,NaN,NaN,NaN,...,-0.010764,-0.157371,-0.238151,0.211408,0.375922,NaN,NaN,NaN,NaN,NaN
2,70d6844ed43ba005b89fce87d16693e93361cd7b7cc1c2...,0.839676,0.331021,-0.529522,-0.903447,-0.360060,-0.097222,-0.025000,-0.052083,-0.097222,...,-0.258921,-0.437890,-0.060038,-0.274673,0.086384,NaN,NaN,NaN,NaN,NaN
3,70d6a05fd3f76b093167c0ada680ba4dddcd897d0d3c6e...,0.123810,0.193234,-0.255046,-0.499877,1.765817,0.503727,-0.584306,-0.145287,-0.098673,...,-0.372706,-0.047767,-0.577874,0.200563,0.853526,NaN,NaN,NaN,NaN,NaN
4,70d6b7ddc54e657816c94559530358a03090d16d7bdf6e...,0.689851,0.279533,-0.333304,-0.774402,0.582608,-0.108637,0.297510,-0.687141,0.075032,...,-0.208565,0.387575,-0.461301,0.646193,-1.592443,NaN,NaN,NaN,NaN,NaN

In [23]:
df_ts.to_pickle("../output/exp18_tsfresh/test_autocorr_3.pkl")

del df_ts,df_test3
gc.collect

In [24]:
#時系列特徴量を作成
fc_parameters = {
#     'partial_autocorrelation': [{'lag': 1},{'lag': 3}, {'lag': 5}, {'lag': 7}, {'lag': 9}],
    "autocorrelation": [{'lag': 1}, {'lag': 3}, {'lag': 5}, {'lag': 7}, {'lag': 12}],
}

df_ts = df_test4.copy()
df_ts = df_ts.fillna(0)
df_ts = extract_features(df_ts, column_id="customer_ID", column_sort="S_2", default_fc_parameters=fc_parameters)

#列名変更
col_list = list(df_ts)
print(len(col_list))
for idx in tqdm(range(len(col_list))):
    col_tmp = col_list[idx].replace('"','')
    df_ts = df_ts.rename(columns={col_list[idx]:col_tmp})
    

df_ts.reset_index(inplace = True)
df_ts = df_ts.rename(columns = {"index":"customer_ID"})
print(df_ts.shape)
df_ts.head()

Feature Extraction: 100%|██████████| 40/40 [53:36<00:00, 80.41s/it]

935

  0%|          | 0/935 [00:00<?, ?it/s]

(203334, 936)

,customer_ID,P_2__autocorrelation__lag_1,P_2__autocorrelation__lag_3,P_2__autocorrelation__lag_5,P_2__autocorrelation__lag_7,P_2__autocorrelation__lag_12,D_39__autocorrelation__lag_1,D_39__autocorrelation__lag_3,D_39__autocorrelation__lag_5,D_39__autocorrelation__lag_7,...,D_144__autocorrelation__lag_1,D_144__autocorrelation__lag_3,D_144__autocorrelation__lag_5,D_144__autocorrelation__lag_7,D_144__autocorrelation__lag_12,D_145__autocorrelation__lag_1,D_145__autocorrelation__lag_3,D_145__autocorrelation__lag_5,D_145__autocorrelation__lag_7,D_145__autocorrelation__lag_12
0,a92350cf849d1eff38de58b7daca20382e5c1a0d6bc864...,0.620133,0.115152,-0.333967,-0.503660,0.190149,-0.216679,-0.197610,0.112718,0.082785,...,0.034341,0.026812,-0.398559,0.041429,0.265185,NaN,NaN,NaN,NaN,NaN
1,a9235d5fd82b131919d046cd61ec19d835cf4ae9451a16...,0.681766,0.095368,-0.147230,-0.539907,-0.517016,0.279103,-0.426569,0.157853,0.131771,...,0.080217,0.222917,-0.677568,0.519863,-0.407665,NaN,NaN,NaN,NaN,NaN
2,a9237873f231f435083d54fe2b2460b9a68ca90e90a1d0...,0.860098,0.227293,-0.380316,-1.001166,0.107556,-0.503799,-0.328529,-0.595545,-0.516524,...,-0.256354,0.232564,-0.370223,0.473870,0.284668,NaN,NaN,NaN,NaN,NaN
3,a92380c42d306cf277ba18d0342a608b5f5831d1587f41...,0.342732,-0.053084,-0.026666,-0.078094,-3.214145,-0.006944,-0.025000,-0.052083,-0.097222,...,0.196308,-0.314854,-0.169812,0.017773,2.069911,NaN,NaN,NaN,NaN,NaN
4,a923a1305ff255b1b98a484d2855ead7174b6ec098bb64...,0.675638,-0.075059,-0.359986,-0.513300,-0.043061,0.100258,-0.045256,-0.254272,-0.460890,...,-0.251551,0.544645,-0.229857,-0.355672,0.458851,NaN,NaN,NaN,NaN,NaN

In [25]:
df_ts.to_pickle("../output/exp18_tsfresh/test_autocorr_4.pkl")

del df_ts,df_test4
gc.collect

In [26]:
#時系列特徴量を作成
fc_parameters = {
#     'partial_autocorrelation': [{'lag': 1},{'lag': 3}, {'lag': 5}, {'lag': 7}, {'lag': 9}],
    "autocorrelation": [{'lag': 1}, {'lag': 3}, {'lag': 5}, {'lag': 7}, {'lag': 12}],
}

df_ts = df_test5.copy()
df_ts = df_ts.fillna(0)
df_ts = extract_features(df_ts, column_id="customer_ID", column_sort="S_2", default_fc_parameters=fc_parameters)

#列名変更
col_list = list(df_ts)
print(len(col_list))
for idx in tqdm(range(len(col_list))):
    col_tmp = col_list[idx].replace('"','')
    df_ts = df_ts.rename(columns={col_list[idx]:col_tmp})
    

df_ts.reset_index(inplace = True)
df_ts = df_ts.rename(columns = {"index":"customer_ID"})
print(df_ts.shape)
df_ts.head()

Feature Extraction: 100%|██████████| 40/40 [27:20<00:00, 41.01s/it]

935

  0%|          | 0/935 [00:00<?, ?it/s]

(111087, 936)

,customer_ID,P_2__autocorrelation__lag_1,P_2__autocorrelation__lag_3,P_2__autocorrelation__lag_5,P_2__autocorrelation__lag_7,P_2__autocorrelation__lag_12,D_39__autocorrelation__lag_1,D_39__autocorrelation__lag_3,D_39__autocorrelation__lag_5,D_39__autocorrelation__lag_7,...,D_144__autocorrelation__lag_1,D_144__autocorrelation__lag_3,D_144__autocorrelation__lag_5,D_144__autocorrelation__lag_7,D_144__autocorrelation__lag_12,D_145__autocorrelation__lag_1,D_145__autocorrelation__lag_3,D_145__autocorrelation__lag_5,D_145__autocorrelation__lag_7,D_145__autocorrelation__lag_12
0,e14ac5a8fd85b8c5c3b8c8dc9159b8420372c92ebdf23a...,-0.258693,0.148610,-0.213893,0.179442,0.088241,NaN,NaN,NaN,NaN,...,-0.385879,-0.658099,-0.458557,-0.266599,0.268310,NaN,NaN,NaN,NaN,NaN
1,e14ae75458f00e9af6673b459c7b6e931c06e3e4866861...,0.384416,0.142527,-0.705569,-0.466033,0.335885,-0.072913,-0.193060,0.185881,-0.239207,...,-0.121340,-0.142011,-0.321411,0.169582,0.421218,NaN,NaN,NaN,NaN,NaN
2,e14af03f04aae2f3ecc9d6cb50a4a0f068cb491a0a0888...,0.791148,0.308013,-0.440909,-0.693795,-1.071709,-0.013799,0.373683,-0.176094,-0.442063,...,0.393325,-0.697513,0.071315,0.151356,-0.888560,-0.006944,-0.025,-0.052083,-0.097222,-1.0
3,e14b0729c55e437be87155790a5b5fb1dd9f54e5c41ea1...,0.480851,-0.022113,-0.378626,-0.292190,-1.558043,-0.097222,-0.025000,-0.052083,-0.097222,...,0.183162,-0.093659,-0.097251,-0.420356,-0.502465,NaN,NaN,NaN,NaN,NaN
4,e14b1f6e466044c5e74cfd4bb7af6350af2f150c40e2dc...,-1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.000000,NaN,NaN,NaN,NaN,-1.000000,NaN,NaN,NaN,NaN

In [27]:
df_ts.to_pickle("../output/exp18_tsfresh/test_autocorr_5.pkl")

del df_ts,df_test5
gc.collect

# データのconcat

In [29]:
# train1 = pd.read_pickle("../output/exp18_tsfresh/train_ts_1.pkl")
# train2 = pd.read_pickle("../output/exp18_tsfresh/train_ts_2.pkl")

# test1 = pd.read_pickle("../output/exp18_tsfresh/test_ts_1.pkl")
# test2 = pd.read_pickle("../output/exp18_tsfresh/test_ts_2.pkl")
# test3 = pd.read_pickle("../output/exp18_tsfresh/test_ts_3.pkl")
# test4 = pd.read_pickle("../output/exp18_tsfresh/test_ts_4.pkl")

train1 = pd.read_pickle("../output/exp18_tsfresh/train_autocorr_1.pkl")
train2 = pd.read_pickle("../output/exp18_tsfresh/train_autocorr_2.pkl")

test1 = pd.read_pickle("../output/exp18_tsfresh/test_autocorr_1.pkl")
test2 = pd.read_pickle("../output/exp18_tsfresh/test_autocorr_2.pkl")
test3 = pd.read_pickle("../output/exp18_tsfresh/test_autocorr_3.pkl")
test4 = pd.read_pickle("../output/exp18_tsfresh/test_autocorr_4.pkl")
test5 = pd.read_pickle("../output/exp18_tsfresh/test_autocorr_5.pkl")

In [31]:
train = pd.concat([train1,train2],axis = 0).reset_index(drop = True)
test = pd.concat([test1,test2,test3,test4,test5],axis = 0).reset_index(drop = True)

In [32]:
# pd.concat([train1,train2],axis = 0).reset_index(drop = True)
display(train.shape)
display(test.shape)

(458913, 936)

(924621, 936)

In [33]:
test['customer_ID'].unique

<bound method Series.unique of 0         00000469ba478561f23a92a868bd366de6f6527a684c9a...
1         00001bf2e77ff879fab36aa4fac689b9ba411dae63ae39...
2         0000210045da4f81e5f122c6bde5c2a617d03eef67f82c...
3         00003b41e58ede33b8daf61ab56d9952f17c9ad1c3976c...
4         00004b22eaeeeb0ec976890c1d9bfc14fd9427e98c4ee9...
                                ...
924616    ffff952c631f2c911b8a2a8ca56ea6e656309a83d2f64c...
924617    ffffcf5df59e5e0bba2a5ac4578a34e2b5aa64a1546cd3...
924618    ffffd61f098cc056dbd7d2a21380c4804bbfe60856f475...
924619    ffffddef1fc3643ea179c93245b68dca0f36941cd83977...
924620    fffffa7cf7e453e1acc6a1426475d5cb9400859f82ff61...
Name: customer_ID, Length: 924621, dtype: object>

In [34]:
train['customer_ID'].unique

<bound method Series.unique of 0         0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...
1         00000fd6641609c6ece5454664794f0340ad84dddce9a2...
2         00001b22f846c82c51f6e3958ccd81970162bae8b007e8...
3         000041bdba6ecadd89a52d11886e8eaaec9325906c9723...
4         00007889e4fcd2614b6cbe7f8f3d2e5c728eca32d9eb8a...
                                ...
458908    ffff41c8a52833b56430603969b9ca48d208e7c192c6a4...
458909    ffff518bb2075e4816ee3fe9f3b152c57fc0e6f01bf7fd...
458910    ffff9984b999fccb2b6127635ed0736dda94e544e67e02...
458911    ffffa5c46bc8de74f5a4554e74e239c8dee6b9baf38814...
458912    fffff1d38b785cef84adeace64f8f83db3a0c31e8d92ea...
Name: customer_ID, Length: 458913, dtype: object>

###  たぶんOK

In [35]:
train.to_pickle("../output/exp18_tsfresh/train_autocorr.pkl")

In [36]:
test.to_pickle("../output/exp18_tsfresh/test_autocorr.pkl")

# 欠損値確認

In [37]:
train.head()

,customer_ID,P_2__autocorrelation__lag_1,P_2__autocorrelation__lag_3,P_2__autocorrelation__lag_5,P_2__autocorrelation__lag_7,P_2__autocorrelation__lag_12,D_39__autocorrelation__lag_1,D_39__autocorrelation__lag_3,D_39__autocorrelation__lag_5,D_39__autocorrelation__lag_7,...,D_144__autocorrelation__lag_1,D_144__autocorrelation__lag_3,D_144__autocorrelation__lag_5,D_144__autocorrelation__lag_7,D_144__autocorrelation__lag_12,D_145__autocorrelation__lag_1,D_145__autocorrelation__lag_3,D_145__autocorrelation__lag_5,D_145__autocorrelation__lag_7,D_145__autocorrelation__lag_12
0,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,0.174903,0.101935,-0.236118,-0.600763,0.007917,-0.097222,-0.025000,-0.052083,-0.097222,...,-0.104158,-0.052005,0.381391,-0.376558,1.735089,NaN,NaN,NaN,NaN,NaN
1,00000fd6641609c6ece5454664794f0340ad84dddce9a2...,0.687463,0.331069,-0.120334,-0.555145,-1.252227,-0.110304,-0.429165,-0.343036,0.388145,...,-0.232295,0.127100,-0.118868,0.054102,0.577802,NaN,NaN,NaN,NaN,NaN
2,00001b22f846c82c51f6e3958ccd81970162bae8b007e8...,-0.088271,-0.081983,0.421744,-0.314059,-0.005768,NaN,NaN,NaN,NaN,...,-0.171315,-0.046841,0.354531,-0.548845,0.831806,NaN,NaN,NaN,NaN,NaN
3,000041bdba6ecadd89a52d11886e8eaaec9325906c9723...,0.790905,0.430614,-0.090225,-0.731281,-1.926653,0.016960,0.163592,-0.094806,-0.150117,...,-0.079493,-0.340753,0.441229,-0.033458,-0.352436,NaN,NaN,NaN,NaN,NaN
4,00007889e4fcd2614b6cbe7f8f3d2e5c728eca32d9eb8a...,0.469236,0.105873,-0.511452,-0.262360,-0.540190,NaN,NaN,NaN,NaN,...,-0.134475,0.082192,0.284313,-0.272151,-0.205607,NaN,NaN,NaN,NaN,NaN

In [38]:
train["D_145__autocorrelation__lag_1"].isnull().sum()

366190

In [44]:
##　3割以上欠損値の列をDrop

drop_list = []

for col in list(train.columns):
    if train[col].isnull().sum() > (len(train) * 0.3):
        drop_list.append(col)
        
display(len(drop_list))

590

In [45]:
train = train.drop(columns = drop_list,axis = 1)
test = test.drop(columns = drop_list,axis = 1)

In [46]:
train.to_pickle("../output/exp18_tsfresh/train_autocorr.pkl")
test.to_pickle("../output/exp18_tsfresh/test_autocorr.pkl")